### ISSUE TITLE
tracking must be opt-in (GDPR) 

### ISSUE THREAD

**Issue by c33s** [gitbutlerapp/gitbutler#2638]
currently a request to sentry is made as soon as i start gitbutler

**Comment by mtsgrd** [comment]
Hey thanks for raising this issue, it's on our radar and a priority given the recent surge in interest! 🙏 

I landed [this change](https://github.com/gitbutlerapp/gitbutler/pull/2620) just a few hours ago, presenting the user with a choice on first start. Note, however, that we still need a couple more commits in order to be opt-in rather than opt-out.

**Comment by krlvi** [comment]
Hi! Thank you for reporting! We got a bunch of unexpected attention which caught us a bit underprepared. I'm currently making a patch release with a min-onboarding flow that allows toggling. 

Keeping this issue opened until we refactor the code so that it does not init any error reporting before an opt-in

**Comment by Byron** [comment]
<img width="1094" alt="Screenshot 2024-04-21 at 14 18 54" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/baebc0fc-f34d-4641-a59b-eabf9aef7cb3">

The picture above was taken with Version 0.11.3 (20240419.070253) and I wonder what the default for these checkboxes in Europe would have to be.

Otherwise, it makes one request to check for automatic updates, and AFAIK this can't currently be configured.

<img width="1031" alt="Screenshot 2024-04-21 at 14 22 40" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/670e878a-0cc0-4d57-8003-ef127fff08d6">

**Comment by c33s** [comment]
in europe it has to be a opt-in

**Comment by krlvi** [comment]
github auto-merged this one since i mentioned it in this PR: https://github.com/gitbutlerapp/gitbutler/pull/3627

The pull request changes the frontend such that analytics are not loaded before the onboarding step is completed as well as identifiable metrics are opt-in.

there is a reference to posthog in the rust code, which I am going to remove entirely in a separate pull request
