### ISSUE TITLE
Show checkboxes beside files and commit message textbox at all times.

### ISSUE THREAD

**Issue by AndreAngelantoni** [gitbutlerapp/gitbutler#2646]
Currently, one must click on Commit changes before one sees the checkboxes beside each modified file and the Commit message textbox.

Further, after clicking the button, all the check boxes are checked. If one wants to commit only one file, one must uncheck the unwanted files.

A better workflow is:
1. Show the checkboxes all the time (like Git Tower does).
2. Show the Commit message box all the time (ditto Git Tower).
3. Check the file(s) to commit.
4. Type commit message or Generate Message button (which are already visible).
5. When step 4 happens, Commit button becomes active.
6. Click Commit.

This workflow seems to me to be the most efficient way to make commits and is especially nice when making multiple commits in a row.

**Comment by Byron** [comment]
As an update, as of Version 0.11.3 (20240419.070253), there is a checkbox on top of all the others which allows to deselect all at once. Otherwise, the current workflow will still need more clicks compared to what's described in this issue though.

<img width="302" alt="Screenshot 2024-04-21 at 16 45 18" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/620db8bc-ff26-4224-a46e-26b952e9a39c">

**Comment by PavelLaptev** [comment]
Let's close this for now.

I have a few concerns:  
- Always-visible checkboxes and commit message boxes (like in Git Tower) may make things easier to access but will clutter the interface. GitButler shows multiple branches with multiple change areas, so this could get messy.  
- Always showing the "commit" box is also not a good idea for the same reason. We need to stay focused on the branch we're working on. Too many similar elements on the screen can be distracting. It's better to show the "commit" box only when you're ready to commit.
