### ISSUE TITLE
Support FIDO security keys for commit signing signing and ssh auth

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2661]

**Comment by stgarf** [comment]
Would love to be able to use Gitbutler but patiently watching this issue because we require Yubikeys. Please let me know if I can participate in alpha/beta testing when you're ready!

**Comment by jokeyrhyme** [comment]
I can confirm that this combination works:

- GitButler 0.10.28 (and perhaps older, this is just where I reproduced it) with "Project settings" -> "Git authentication" -> "Use a Git executable"
- `ssh-agent` setup with the SSH_AUTH_SOCK environment variable set for all new processes in my login session
- Yubikey security key setup via `ssh-keygen -O resident -t ed25519-sk`
- corresponding public key enrolled in my GitHub settings

For any SSH request to GitHub, my security key flashes and nothing happens until I tap the security key

**Comment by alexandervaneck** [comment]
@jokeyrhyme How exactly did you setup `ssh-agent`?

Did you use https://github.com/drduh/YubiKey-Guide?tab=readme-ov-file#ssh-agent-forwarding ?

**Comment by jokeyrhyme** [comment]
@alexandervaneck 

my default shell is [nushell](https://www.nushell.sh/), and I've got it configured to start `ssh-agent` if it isn't already running and load its environment variables into dbus/systemd/launchd so they'll take effect in future processes (the way my system launches them, anyway), and also runs `ssh-add -K` if there is a Yubico security key plugged in:

- https://gitlab.com/jokeyrhyme/dotfiles/-/blob/bd615428b36fdfc7e6ebdec5ae66c9d8ac8afda2/config/nushell/interactive.nu#L25-84
- https://gitlab.com/jokeyrhyme/dotfiles/-/blob/bd615428b36fdfc7e6ebdec5ae66c9d8ac8afda2/config/interactive.sh#L62-98 (older bash/zsh equivalent that has not been tested for years)

so, my workflow is to open a terminal, and my keys are PIN-protected so `ssh-add -K` prompts to input the PIN, and once my shell prompt appears, I can then run GitButler and it'll have the correct SSH_AUTH_SOCK environment variable

it's worth learning how to inspect the environment variables actually available to running processes, if you do not already do so for debugging this kind of thing

**Comment by Qix-** [comment]
The system executable auth flow now allows for `GIT_SSH` and `GIT_SSH_COMMAND` to be specified, too. Along with the above I'm going to close this as that's probably the preferred method to set up different authentication methods on your respective development machines.

Let me know if something was missed here, or if for some reason something isn't working with regards to FIDO keys!

**Comment by OJFord** [comment]
For macOS it looks like the key from script linked above would be the `launchctl setenv SSH_AUTH_SOCK ...`, but with that GitButler's still launching with some default value like:
```
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.HTZpb2Ez4q/Listeners
```

not the correct value.

Do you have GPG signing working too? That just errors 'no such file or directory' (doesn't tell me what it's trying) when I click test.

Launching from a shell for now, just to have it work at least.

**Comment by Byron** [comment]
That's interesting! Could you open this as new issue so we can keep track of it?

A quick check revealed that nothing is done explicitly with `SSH_AUTH_SOCK`, so a solution probably isn't going to be very obvious.

**Comment by jokeyrhyme** [comment]
> For macOS it looks like the key from script linked above would be the `launchctl setenv SSH_AUTH_SOCK ...`, but with that GitButler's still launching with some default value like:
> 
> ```
> SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.HTZpb2Ez4q/Listeners
> ```

Yeah, my trick for that is just above the previously-highlighted lines but in the same scripts:

- we detect if the current SSH_AUTH_SOCK was set by the `ssh-agent` started by `launchd` (which is the macOS built-in which isn't sufficient for FIDO keys) and unset it: https://gitlab.com/jokeyrhyme/dotfiles/-/blob/bd615428b36fdfc7e6ebdec5ae66c9d8ac8afda2/config/interactive.sh#L57-60

- elsewhere in the scripts, we always check to see if the homebrew installation of `ssh-agent` ( https://gitlab.com/jokeyrhyme/dotfiles/-/blob/bd615428b36fdfc7e6ebdec5ae66c9d8ac8afda2/config/interactive.sh#L64-68 ) and `ssh-add` ( https://gitlab.com/jokeyrhyme/dotfiles/-/blob/bd615428b36fdfc7e6ebdec5ae66c9d8ac8afda2/config/interactive.sh#L91-95 ) are available, preferring to use those specifically instead of whatever is in PATH

macOS is kinda' a mess, and honestly I wouldn't be using it all if my employer gave me a Linux option

I acknowledge that what I have is an inelegant hack, so I very much hope someone else offers a better approach 🥺

**Comment by Byron** [comment]
Thanks for the details, and I'd hope that once I get into this more (which will happen eventually), I will understand what's really going on here.

Regarding the 'inelegant hack', I think that if Git works with it, so should GitButler. If Git does indeed work with it, could you create a new issue with the information provided thus far so it can be tracked? Otherwise it's likely to get lost.
Thanks again for your help.

**Comment by jokeyrhyme** [comment]
Okay, I raised https://github.com/gitbutlerapp/gitbutler/issues/4140
