### ISSUE TITLE
Feature request: Bare Repository Support

### ISSUE THREAD

**Issue by floork** [gitbutlerapp/gitbutler#2704]
Hey Gitbutler Team,

I ran into an issue trying to open a branch in a bare repository using Gitbutler. Here's the error message I got: ![image](https://github.com/gitbutlerapp/gitbutler/assets/48620727/e46658e9-889f-4a16-9f07-d3f252aec534)

It'd be super helpful if you could make it possible to create branches directly in bare repositories. That would make my workflow a lot smoother.

Thanks a bunch!

**Comment by krlvi** [comment]
Hey @floork ! We had not considered bare checkouts. I would love to hear more about your use case

**Comment by floork** [comment]
Hi @krlvi,

Thanks for reaching out! Let me give you some more insight into how I work.

So, I'm all about using worktrees to tackle issues head-on and keep things organized. They've been a game-changer for me in managing my projects effectively.

But then I stumbled upon Gitbutler and its virtual branches feature got me intrigued. I see a lot of potential there, especially for handling feature development within those feature branches.

Here's the thing: if I could create branches directly in bare repositories with Gitbutler, it would take my workflow to the next level. It's like having the best of both worlds – the flexibility of worktrees and the power of virtual branches, all in one place.

So yeah, that's where I'm coming from. I hope that gives you a clearer picture of why I'm excited about this idea!

**Comment by Byron** [comment]
Just as an update, the error messages improved since then.

As of Version 0.11.3 (20240419.070253) , it looked like this:

<img width="243" alt="Screenshot 2024-04-21 at 17 32 38" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/fdac5669-e59a-46e7-afc1-f32521609e62">

And one of the next releases should show something like this to make clear what's going on.

<img width="304" alt="Screenshot 2024-04-21 at 17 39 24" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/bbc0c9c8-6d1c-4054-aec8-dcc8fcfc7a84">

Supporting a bare repository with worktrees is definitely an interesting feature though! As long as only one worktree is checking out the `gitbutler/integration` branch, it should have a chance to work.

**Comment by floork** [comment]
Great! Thanks for the affort

**Comment by Byron** [comment]
Even though this issue is closed, it lives on here:

* #4254
