### ISSUE TITLE
It should be possible to open an already setup repository on a different computer.

### ISSUE THREAD

**Issue by powerpaul17** [gitbutlerapp/gitbutler#2722]
1. I setup Gitbutler on a repository on computer A.
2. I synchronize my folder to comptuer B.
3. When I open the repo with Gitbutler on computer B, it overwrites the virtual branches.

**Comment by krlvi** [comment]
this is an interesting usecase. right now it is not very easy to support this because the app saves state in 2 places - its namespaced refs (ls -l .git/refs/gitbutler) within the repo, as well as the app data dir (https://docs.gitbutler.com/development/debugging#data-files) 

We were talking a bit internally about potentially keeping everything in once place (within the project dir) but it will take us a little bit of time until we get there (requires a fairly big refactor of the app internals)

**Comment by Caleb-T-Owens** [comment]
@powerpaul17 we now store all relevant app state in the `.git` directory so this should now behave much better. Feel free to open another issue if there are any other issues that you find with this type of setup.

**Comment by powerpaul17** [comment]
Thats great news, I'll check it out. Thanks for the effort :tada:
