### ISSUE TITLE
On MacOS gitbutler menubar icon is shown in the wrong place

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2745]
![ezgif-5-dcf92dc61f](https://github.com/gitbutlerapp/gitbutler/assets/4030927/89bb6c05-7d09-47bf-b12e-fe9823affb66)

discord discussion:
https://discord.com/channels/1060193121130000425/1073202153163857920/1207966894431404104

**Comment by warpdesign** [comment]
Stumbled upon this one too: thought this was related to the notch maybe.

**Comment by redomar** [comment]
Possibly related with #2596

**Comment by Caleb-T-Owens** [comment]
I know it's a bit of an Apple app trope to put your app's icon in the tray, to the extent that I've ended up with so many that half of the ones on the end don't get displayed on my laptop's screen because they're eaten up by the notch.

The options available when you click on the icon are "Hide" and "Quit" - both duplicate behaviours that macOS already provides. This makes me wonder - why have it at all?

**Comment by krlvi** [comment]
now that i think about it, many other dev tools don't have menubar icons (e.g. vscode, terminals etc), so indeed this may be something to reconsider.

**Comment by krlvi** [comment]
another tray related issue https://github.com/gitbutlerapp/gitbutler/issues/2702

**Comment by krlvi** [comment]
resolved in https://github.com/gitbutlerapp/gitbutler/pull/2785
