### ISSUE TITLE
Exclude gitignored files from filesystem watching

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2798]
Currently the app pickup filesystem events from all files within the repo and then filters out ignored files on an event basis. It would be more efficient to not listen to ignored files / directories in the first place.

It needs to of course handle changes to what is gitignored accordingly without the need to restart the process

**Comment by allain** [comment]
In addition to this being a performance improvement it would allow the import of repositories that have read-only directories gitignored. In my case, a ./data folder that contains mongodb data is causing the import to fail.

**Comment by Byron** [comment]
Regarding `.gitignore` performance, I don't expect this to be as much of an issue anymore after the latest refactors. Watching only folders that aren't excluded is something that will not be necessary, it's fine to watch all and then run it through the exclusion filter (which is always up-to-date as it opens a fresh repository each time).

> Currently the app pickup filesystem events from all files within the repo and then filters out ignored files on an event basis. It would be more efficient to not listen to ignored files / directories in the first place.
> 
> It needs to of course handle changes to what is gitignored accordingly without the need to restart the process

This should be fixed with [this PR](https://github.com/gitbutlerapp/gitbutler/pull/3568).

I am closing this issue in anticipation that it is solved, but please feel free to comment or reopen if there is the need.
