### ISSUE TITLE
The GUI doesn't update with changes

### ISSUE THREAD

**Issue by fstackgeek** [gitbutlerapp/gitbutler#2815]
Setup: Ubuntu 23.04

The GUI doesn't update when a file changes, or even when I do something inside the app itself.
For example, when I drag a file to a new virtual branch, it doesn't do anything until I reload the window, then it shows the new branch. And this is true for creating, editing, or deleting virtual branches. But moving the branches (lanes) works fine.

I love the thinking behind GB, and I have wanted these features for so long, so I'm very eager to be able to use it.

Thank you all

**Comment by mtsgrd** [comment]
Sounds like it could be a problem with the file watcher. Would you mind taking a look in the logs to see if anything stands out? https://docs.gitbutler.com/development/debugging

**Comment by jboardman367** [comment]
I have the same behavior with 0.10.17 on ubuntu 22.04, and it does seem to relate to the file watcher.
```
2024-02-26T01:47:03.309333Z ERROR gitbutler-app/src/watcher.rs:72: watcher error error=Other(failed to run dispatcher

Caused by:
    0: failed to run file change dispatcher
    1: failed to start watcher
    2: OS file watch limit reached. about ["/home/.../node_modules/..."]) project_id=226e2f94-8623-46e8-b5d3-65db2909bd5a
2024-02-26T01:47:04.135593Z ERROR fetch_from_target: gitbutler-app/src/virtual_branches/commands.rs:653: error=failed to post event
```
When I remove the repo that caused the error and opened the gitbutler repo instead, the drag and drop worked.

It would be nice if the file watcher respected `.gitignore` so that it doesn't try to watch the entirity of something like a `node_modules`.

**Comment by Byron** [comment]
Thanks for looking into this, knowing that the watcher failed as it's a constrained system resource is very helpful!

As of the latest Version 0.11.3 (20240419.070253) or newer, the watcher has been overhauled, and I'd expect failures to watch a directory to become visible in the user interface now. That way, the UI should not even get into the unresponsive state described here.

Would you be able to try again?

**Comment by jboardman367** [comment]
Thanks for the update,
I have tried the repo that I was originally having problems with and it works beautifully now. I see no errors relating to file watching and everything appears to be in working order.

**Comment by Byron** [comment]
Thats great to hear :)!

Since @fstackgeek is on Ubuntu 23.04, maybe this issue can't be closed just yet until we heard back from them.

**Comment by fstackgeek** [comment]
@Byron Thank you for your response. I will test this as soon as possible, and get back to you. Although now I am on Ubuntu 23.10

**Comment by Qix-** [comment]
Hey, yeah we've had some significant improvements to the file watching situation over the last few weeks and months. I'm going to go out on a limb here and say that these sorts of issues are _probably_ fixed by now. Trying to clean up the tracker a bit so I'll close this for now - however if you're still facing issues with it please comment here and I'll open it back up again!

Thanks for the report :)
