### ISSUE TITLE
Upgrade from 0.10.11 to 0.10.12 failed

### ISSUE THREAD

**Issue by datamann** [gitbutlerapp/gitbutler#2833]
I just upgraded from 0.10.11 to 0.10.12 and when starting Gitbutler for the first time after the upgrade I got this error:
![Screenshot Gitbutler](https://github.com/gitbutlerapp/gitbutler/assets/5736435/a1b13f55-3eba-4c50-b855-9b1a030cf85c)

I tried to remove the repository but now I'm not able to add the repository back making the app useless. I will try to remove this version completely and reinstall it.

**Comment by datamann** [comment]
I completely removed Gitbutler, reinstalled it, logged in, added the same repository, and got the same error msg.

**Comment by krlvi** [comment]
hey @datamann, i am so sorry for this. I am investigating why this may be, but in the meantime here are some suggestions for mitigating:
- Consider removing the project and re-adding it again. 
- If you need to extract work out of vbranches, you may get refs to them here `ls -l .git/refs/gitbutler`
- It may be worth deleting the [data folder](https://docs.gitbutler.com/development/debugging) of the app

Let me know if any of these help

**Comment by datamann** [comment]
Thank you for your fast respons!
I've tried to remove the data folder ~/Library/Application Support/com.gitbutler.app/ but had no effect. I have however not tried to remove .git/refs/gitbutler

**Comment by krlvi** [comment]
the `.git/refs/gitbutler` are just for you to get your data out of the virtual branches in case you have something that you need immediatelly

**Comment by datamann** [comment]
BTW
Just let me know if you need me to test something.

**Comment by Byron** [comment]
Is this still the case with the latest version of GitButler, Version 0.11.3 (20240419.070253) at the time of writing?

Otherwise, it looks like the repository is checked out, i.e. has its `.git/HEAD` pointing to `.git/refs/heads/gitbutler/integration`, but that ref does not seem to exist. Git should also have problems in this repository, as `HEAD` is expected to point to a valid ref or commit unless it's a freshly initialized repository.

Maybe you could share a `git status` on the project that shows these issues.

**Comment by krlvi** [comment]
since it has been a while I will close this issue. I think it should definitely be fixes by now. You are always welcome to create a new github issue if this problem resurfaces.
