### ISSUE TITLE
 Failed to push branch: Something went wrong

### ISSUE THREAD

**Issue by alexthotse** [gitbutlerapp/gitbutler#2844]
Been stuck on this error every since I tried pushing my work to gitlab.
Any advice?

**Comment by Byron** [comment]
Error handling and authentication options have improved greatly in the meantime. Would you be able to try again using the latest version?

**Comment by stijnvanderlaan** [comment]
On the nightly build (Version 0.5.502 (20240528.031518) stuck on  "Something went wrong". No errors in log.
<img width="218" alt="Screenshot 2024-05-28 at 15 34 20" src="https://github.com/gitbutlerapp/gitbutler/assets/20322260/512b5f2f-e8b0-45a6-a952-b0094c304683">

**Comment by Byron** [comment]
Could you try again with 0.5.503? The screenshot of the error message looks like it's a failure during layout, which can happen if something panics, which also wouldn't be visible in the logs, even though it might be visible in the `tokio-console`.

**Comment by krlvi** [comment]
Fetching and pushing were some of the bigger issues that were plaguing the app a few months back. The biggest change since then is that by default, the app will now fork-exec the git binary on the path for fetching and pushing, with has solved the vast majority of issue. Im gonna close this issue since it has been a while and we haven't heard back.

If you still have issues, you are more than welcome to open a new github issue. Thanks again for reporting this in the first place!
