### ISSUE TITLE
[CI bug][drive-by recommendation] An incorrectly configured `check-rust` job Unified gate setup recommendation

### ISSUE THREAD

**Issue by webknjaz** [gitbutlerapp/gitbutler#2848]
I see the project's CI setup has a job called `check-rust` that is set up *incorrectly*.
It seems to have been added in hopes to act as a unified gate for use in the branch protection, allowing only having a single GHA job listed in the repo settings. However, with the way it's currently set up, this job is always treated by GitHub's branch protection as successful — whether it's skipped because the job dependencies failed or actually got executed. I've seen this problem so many times that I came up with a GitHub Action that allows setting up a job that actually works as an ultimate gate for letting PRs go through merge or blocking them reliably.

Here it is, with a few paragraphs of explanation: https://github.com/marketplace/actions/alls-green/#why. Wiring it up properly may allow you drop the unnecessary statuses from the branch protection rules leaving only one GHA status as required.

**Comment by Qix-** [comment]
Hey, totally - this makes complete sense. It was because GitHub doesn't allow you to specify matrix jobs as required checks, and there's no way to tell GitHub "hey, everything either needs to be green, or skipped" in order to allow auto-merge to work. I hold the opinion this means Github Action's design is broken, personally.

This looks nice, thanks for posting it. I'll work on a PR sometime this week, or you're welcome to also update our config to handle it. Immensely appreciated either way :)
