### ISSUE TITLE
Allow names of objects to be copied to the clipboard

### ISSUE THREAD

**Issue by Glenn-townsend-music** [gitbutlerapp/gitbutler#2853]
By objects, I mean branch names, file names, commit messages.

Currently, you can't double-click or click & drag to select names and there are no menu options to copy the names.

Use cases:

I see a change in a file. I want to be able to open that file in my IDE. Currently I have to type the name in to the File Open dialogue, which is a pain. Would be so much faster and far less prone to mistakes if I could copy the file name.

I need to change a commit. Currently I have to undo it, make the adjustments and re-commit. Not only do I have to re-type the commit message, but I have to remember it as it no longer exists.

I want to look at a branch in github and again, I have to type the name in.

Apologies if I'm able to do any of these things in the current version.

**Comment by mtsgrd** [comment]
Hey, thanks for the feedback. Some of the things you mention should already be possible, but I agree that we could make it easier to copy file path (relative & absolute), and branch names.

About commit messages, I just tested this and it seems possible only in other views than "workspace". The reason is because  we've added functionality to drag & drop commits between branches (only head commit). In other places I can click and drag to select the commit title/message.

Also, not sure what IDE you use, but we have an "Open in VS Code" menu item when right clicking on a hunk. Does that work for you?

Furthermore, I think undoing commits will now preserve the commit message so it's easy to recommit things. You can also drag new changes onto the head commit to amend it.
