### ISSUE TITLE
doesn't use already configured git authentication by default

### ISSUE THREAD

**Issue by rbtcollins** [gitbutlerapp/gitbutler#2901]
I see there are some possibly duplicate bugs - please do mark as a dupe if this is. This bug however isn't about authentication failing! rather it is about the design choice to have git-butler create its own key.

I note that git-butler creates its own key by default. (if it matters, my ssh key is ~/.ssh/id_ed25519 - and git-butler did not overwrite or create that).  The [docs](https://docs.gitbutler.com/troubleshooting/fetch-push#use-locally-generated-ssh-key)  say that this is placed in the app data dir, but at least for me there is no sign of it even though there is a key ID present in the 'git stuff' preferences page:

```
/home/robertc/.local/share/git-butler/
/home/robertc/.local/share/git-butler/hsts-storage.sqlite
/home/robertc/.local/share/git-butler/storage
/home/robertc/.local/share/git-butler/storage/salt
/home/robertc/.local/share/git-butler/deviceidhashsalts
/home/robertc/.local/share/git-butler/deviceidhashsalts/1
```

https://docs.gitbutler.com/troubleshooting/fetch-push#use-an-existing-ssh-key states that an existing key can be configured, but no information on how to do that is supplied. 

It seems likely to me, that at least for some time, git-butlers TAM will mainly consist of adventurous developers with existing git setups - defaulting to utilising the existing git auth setup, which one assumes *already works from the CLI*, would make adoption of this interesting tool much easier.

**Comment by krlvi** [comment]
Hey @rbtcollins, sorry for not getting back sooner on this issue. Ultimately, yes you are right. Originally, the design choice for the app to create it's own key was made in an effort to make it easier to get started using ssh remotes (for people using https remotes, at the time, GitButler was not able to handle the auth).

Since then, we have implemented a fork-exec flow that the app uses for fetching and pushing. This approach ended up being not just more convenient and performant but also more secure, since no new keys are created, plus the app can use existing platform specific tooling for managing secrets. With that in place, the key generation flow no longer exists since a couple of months ago. 

I really appreciate this conversation, even thought we weren't able to respond in here on time. Let me know if you have any other thoughts or questions on this. Otherwise we can close this issue. Thanks

**Comment by krlvi** [comment]
Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.
