### ISSUE TITLE
Wrong git diff

### ISSUE THREAD

**Issue by renja-g** [gitbutlerapp/gitbutler#2907]
The way GitButler displays the git diff in this case is very confusing
It looks like I added a network to my network

![image](https://uploads.linear.app/68aff581-b3ce-490e-a760-537f27ff0cad/6fd81542-edaf-46ad-9e72-b00d19d6c76a/3dea75c2-9378-4a8c-8e0b-7163dade8c0b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY4YWZmNTgxLWIzY2UtNDkwZS1hNzYwLTUzN2YyN2ZmMGNhZC82ZmQ4MTU0Mi1lZGFmLTQ2YWQtOWU3Mi1iMDBkMTlkNmM3NmEvM2RlYTc1YzItOTM3OC00YThjLThlMGItNzE2M2RhZGU4YzBiIiwiaWF0IjoxNzA4ODgxNTMwLCJleHAiOjMzMjc5NDQxNTMwfQ.CgDh6jV1QoaWyIBXbRm1zxepMmeoDUkqjSv63ypLZvM)

![image](https://uploads.linear.app/68aff581-b3ce-490e-a760-537f27ff0cad/ee77e322-2ac6-4b6f-bde7-b4e29ba5a65e/5f9a0eee-29b7-478f-b43c-d6748ac3aa1e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY4YWZmNTgxLWIzY2UtNDkwZS1hNzYwLTUzN2YyN2ZmMGNhZC9lZTc3ZTMyMi0yYWM2LTRiNmYtYmRlNy1iNGUyOWJhNWE2NWUvNWY5YTBlZWUtMjliNy00NzhmLWI0M2MtZDY3NDhhYzNhYTFlIiwiaWF0IjoxNzA4ODgxNTMwLCJleHAiOjMzMjc5NDQxNTMwfQ.09QRKk7bI8AqD22bJxFLNG2n9hoAy5-YOhGRpDNLSn4)

**Comment by krlvi** [comment]
working on this today

**Comment by krlvi** [comment]
hey - quick update here, this should be addressed in this PR: https://github.com/gitbutlerapp/gitbutler/pull/2908
Gonna release this later today. Because this changes the format of the hunk allocations (as they are persisted), migrating to the new flow happens when you have a clean workspace (no active or stashed vbranches)

**Comment by schacon** [comment]
test
