### ISSUE TITLE
Performance issues with large git indexes

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2938]
Repositories that have high cardinality of files (20K+ of distinct files) are slow to operate on. 
Initial investigation indicates that this is related to frequent operations on a large index.

Discord thread:[https://discord.com/channels/1060193121130000425/1073202153163857920/1211957896968142912](https://discord.com/channels/1060193121130000425/1073202153163857920/1211957896968142912)

**Comment by ganwell** [comment]
I presented GitButler to my colleagues and they of course immediately tried to use it on our largest repository. Move changes between virtual-branches takes over two seconds. So I started to dig into this. And ran profiler.

92% of the time is spent in [git_diff_tree_to_workdir](https://libgit2.org/libgit2/#v0.20.0/group/diff/git_diff_tree_to_workdir).

![perf](https://github.com/gitbutlerapp/gitbutler/assets/1186530/ff74a898-976c-4a9f-9dd5-172b10ae0e7a)

So I am currently reading the code and thinking about the issue. I just wanted to give feedback early.

**Comment by krlvi** [comment]
hey! thanks for the profiling info! how many tracked files do you have? `git ls-files | wc -l` 
The app updates the index too frequently, and one immediate optimization I was working on is to detect noops and not write in those cases.

**Comment by krlvi** [comment]
something that we will try out soon, is see if can use gitoxide for the heaviest operations https://github.com/Byron/gitoxide/issues/1287 but either way we'd need to make the flow efficient the the the snappiest possible experience

**Comment by ganwell** [comment]
# git ls-files | wc -l
11611

It seems like rehashing a lot, we also have a lot large snapshot-test files. (See findings)

**Comment by ganwell** [comment]
> The app updates the index too frequently, and one immediate optimization I was working on is to detect noops and not write in those cases.

Do I have to switch to a new issue? The problem I am looking into seems more like it is doing too much work in a case that is not a noop.

**Comment by ganwell** [comment]
I think I found the problem. In [git_diff_tree_to_workdir](https://libgit2.org/libgit2/#v0.20.0/group/diff/git_diff_tree_to_workdir) the hashes from the workdir (filesystem) are not cached. It will rehash every unchanged file. The cache seems to be missing because we compare to a (virtual) tree. It seems difficult to fix that outside libgit2.

**Comment by ganwell** [comment]
If we use [git_diff_tree_to_workdir_with_index](https://libgit2.org/libgit2/#v0.20.0/group/diff/git_diff_tree_to_workdir_with_index) we get a cache. I guess this means we could fix this, by reverting the effect of staged data before doing the diff. I assume users shouldn't stage anything when using GitButler anyways.

```patch
diff --git a/gitbutler-app/src/git/repository.rs b/gitbutler-app/src/git/repository.rs
index 7893c12b..db025c65 100644
--- a/gitbutler-app/src/git/repository.rs
+++ b/gitbutler-app/src/git/repository.rs
@@ -148,7 +148,7 @@ impl Repository {
         opts: Option<&mut git2::DiffOptions>,
     ) -> Result<git2::Diff<'_>> {
         self.0
-            .diff_tree_to_workdir(old_tree.map(Into::into), opts)
+            .diff_tree_to_workdir_with_index(old_tree.map(Into::into), opts)
             .map_err(Into::into)
     }
 ```

**Comment by krlvi** [comment]
Thank you so much for showing this @ganwell! You are right that staging is not something that is in the flow. I am gonna merge your patch to do some testing with the nightly build over the weekend 🙇

**Comment by ganwell** [comment]
> Thank you so much for showing this @ganwell! You are right that staging is not something that is in the flow. I am gonna merge your patch to do some testing with the nightly build over the weekend 🙇

I saw the failure at #3158. I checked `cargo test` and came to the conclusion the index should be updated before being used.

### Steps

- I updated my code to test lastest version b594c685
- Checked with the profiler that the problem still exists
- Run the `cargo test` with the old patch -> fails
- Added `index.update_all` the to `diff_tree_to_workdir`
- Checked the profiler: It does not show reindexing. The GUI also feels fast
- Run the `cargo test` with the old patch -> ok

### Considerations

- I read to code and could not find anything that could be hurt by the `update_all`
- I am kind of confused why the index never gets updated currently, but the index is only used with a checkout. Maybe on checkout it gets updated automatically
- I currently assume that if the index does not exist it is created on `diff_tree_to_workdir_with_index`, but I haven't read to code the check that. At least in unittests all conditions seem to be met.
- **Important**: I still haven't tested what happens if a user would **stage** something. Maybe we could just reset any staging, like additional commits get removed if the repo is in GitButler Mode

```patch
diff --git a/gitbutler-app/src/git/repository.rs b/gitbutler-app/src/git/repository.rs
index 7893c12b..0017fe41 100644
--- a/gitbutler-app/src/git/repository.rs
+++ b/gitbutler-app/src/git/repository.rs
@@ -147,8 +147,11 @@ impl Repository {
         old_tree: Option<&Tree<'_>>,
         opts: Option<&mut git2::DiffOptions>,
     ) -> Result<git2::Diff<'_>> {
+        if let Ok(mut index) = self.0.index() {
+            index.update_all(vec!["*"], None)?;
+        }
         self.0
-            .diff_tree_to_workdir(old_tree.map(Into::into), opts)
+            .diff_tree_to_workdir_with_index(old_tree.map(Into::into), opts)
             .map_err(Into::into)
     }
 ```

**Comment by krlvi** [comment]
thanks! let me get that patch in - i got distracted with other things. I really appreciated your help here, i wanna buy you a beer!

**Comment by ganwell** [comment]
> regarding staging, i think it is already a corner case that may haver unknown outcomes - i will investigate

GitButler reverts staging as soon as the GUI does its update-cycle. I to my understanding that means using the index is save. If nothing is staged `diff_tree_to_workdir` and `diff_tree_to_workdir_with_index` should be equal.

**Comment by krlvi** [comment]
Once again, than you for debugging and profiling this @ganwell ! I have merged your patch and if you spot anything else, you are welcome to open a PR directly too. I think i'm gonna close this issue.

If you would like, ping me on kiril@gitbutler.com and i will make sure that multiple beers get delivered to your door 🍻!
