### ISSUE TITLE
Add support for multiple Gitbutler windows

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#3012]
Could we have more than one gitbutler window? I work with two different repos (app and iaac) at the same time quite often. Switching between repos is possible, but feels clunky. Repository tabs or even better separate windows would be a great addition.

via: andy_25104

https://discord.com/channels/1060193121130000425/1176875943873232947/1214065195698229309

**Comment by mtsgrd** [comment]
This is something we definitely want to add, but at the moment we are prioritising bugs and product stability. I would estimate that we will get to this within 3-4 weeks at most.

**Comment by Byron** [comment]
This is implemented, it's just a hidden feature at the moment (but available to everyone).

**Comment by OPeyrusse** [comment]
Finding this after the battle, if this is already available but hidden, how can we enable it? Or should we just wait a bit before enjoying this? :smile:

**Comment by Byron** [comment]
You can use `Alt + LMB` on the project in the list - instead of opening the project in the current window, it will open it in a new Window. There are some issues about displaying which projects are open, but generally the feature is working.
Please also note that it's experimental and can change at any time.

https://github.com/user-attachments/assets/064e272a-545c-4765-8e58-c90d4eebe5f2

Meanwhile, please enjoy :).

**Comment by OPeyrusse** [comment]
Thanks for the tip. Will do so, living dangerously :wink:

**Comment by ericclemmons** [comment]
This doesn't work with v3 :'(

**Comment by Byron** [comment]
Yeah, unfortunately it stopped working when switching to V3, but the underlying system still supports it.
Thus, I believe it will come back just because it's so practical, but I guess it needs a motivating use-case.

My feeling is that once there is a `but` CLI where `but .` will open up GitButler on a given directory, then at the latest that would open its own Window again. And all that while being a tried and proven way of interacting with user interfaces, like `zed .` and `code .`.
