### ISSUE TITLE
Cargo fmt not working in app/main.rs

### ISSUE THREAD

**Issue by Qix-** [gitbutlerapp/gitbutler#3039]
Might be affecting other things in app/, too. Noticed it late this afternoon, will need to investigate what's going on.

**Comment by Byron** [comment]
This typically happens if lines are too long. Then `rustfmt` shows unfortunate behaviour and just bails on the entire file without saying what's going on.

A quick way to fix this is to change [the line length](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=width#max_width) to something larger, then format everything.

I also checked `tauri/src/main.rs` and saw that it seems to format fine by now. There were, however, a few files that didn't and I fixed this in via #3584 .

Does that work for you?

**Comment by Qix-** [comment]
Yeah, thanks for the follow-up :)
