### ISSUE TITLE
Zombie processes left after closing gitbutler

### ISSUE THREAD

**Issue by vladdu** [gitbutlerapp/gitbutler#3064]
I don't know if it's an application issue, or a Tauri one. There are many zombie processes left around, and they are not idle either, but use CPU.

**Comment by Qix-** [comment]
Which platform are you on, and which version of GitButler are you using?

**Comment by vladdu** [comment]
Oops, sorry, I forgot to mention that. It's on Ubuntu 20.04, and I gitbutler is version 0.10.13.

**Comment by krlvi** [comment]
> Oops, sorry, I forgot to mention that. It's on Ubuntu 20.04, and I gitbutler is version 0.10.13.

When you have the chance, could you try out the latest build? (currently 0.10.27). Earlier, the app had a tray menu item and we had it configured to not terminate the process upon closing the window (mirroring the MacOS behavior). We have since then removed the tray icon and the app should now close correctly

**Comment by vladdu** [comment]
Yes, it looks it works fine now. Thanks!
