### ISSUE TITLE
Application behave unexpected when there is `.git` directory inside repository used as project

### ISSUE THREAD

**Issue by keinsell** [gitbutlerapp/gitbutler#3178]
Long story short, I was self-hosting a Supabase which required to be cloned before deployment so I've cloned it to repository which was mine Gitbutler project, the repo didn't shown up which is fine. Later, application did not respond to my actions (I could move one file, then restart app, move another file and so on) not sure what causes such case, and I cannot reproduce it on-call however something is wrong down there. This may be also caused by submodules that we're used in some past point of time inside such repository. I think the screencast demonstrates the actual issue.

[Screencast from 2024-03-17 16-04-21.webm](https://github.com/gitbutlerapp/gitbutler/assets/41811819/18cf43ce-6220-4ed1-9438-7d5c42c7287a)

Version: `0.10.16`
Platform: Arch Linux (CachyOS)
Submitted Ticket Message: `a1071788-5322-4eaf-95e7-9c72ebc3666d`

**Comment by Byron** [comment]
Thanks for reporting!

It's clear from the video that the application isn't responding as it should, and [the log files](https://docs.gitbutler.com/development/debugging#logs) could probably tell more.

Since submodules aren't supported, with the most recent version of GitButler (0.11.3 at this time) one might not be able to add the project at all.

Maybe you could retry with the latest version, and if it fails, share the log assuming it contains errors? Another test could be to remove and re-add the project to see if it now would be rejected based on submodules being present.

Thanks a lot for your help.

**Comment by krlvi** [comment]
@keinsell thank you for reporting this in the first place. Since this doesnt seem to be a problem currently im going to close this issue. If this problem re-surfaces feel free to open a new issue (or if you come across another problem)
