### ISSUE TITLE
Refine UI output when "Add a new project" takes a long time

### ISSUE THREAD

**Issue by koppor** [gitbutlerapp/gitbutler#3281]
I try to add a project, then I get the spinner:

![grafik](https://github.com/gitbutlerapp/gitbutler/assets/1366654/9073a255-423e-46be-bca3-8c58371da151)

The text reads "Verify valid Git repository in selected folder before importing". I think, that should be "Verifying valid Git repository in selected folder before importing.", because the operation is ongoing (and not going to happen)

**Comment by koppor** [comment]
The console output is

```
2024-03-22T08:33:56.261249Z  INFO list_projects: gitbutler-app/src/projects/commands.rs:132: close time.busy=10.7µs time.idle=30.3µs
2024-03-22T08:34:21.503418Z  INFO add_project: gitbutler-app/src/gb_repository/repository.rs:347: created new session project_id=810b1d12-9a4d-453c-8459-9fe0458e1498 session_id=93dd3c7a-fcda-435a-8002-438848679c9a path="/mnt/c/git-repositories/JabRef"
```

**Comment by Byron** [comment]
When I tried the Linux repository (#3512), it also took a long time, seemingly because gravatar image were eagerly loaded for all of the 30k unique authors.
Is the project you were using for testing public, so that I could try it as well? Thank you.

**Comment by koppor** [comment]
Yes, the project is public and available at https://github.com/jabref/jabref/.

**Comment by Byron** [comment]
Thanks for helping!

I think the issue here was that there were internal failures that weren't communicated very well. When trying this now, the program fails with a popup saying that repositories with submodules aren't supported.

Thus, I am closing this issue as fixed, but please feel free to keep commenting or to reopen in case I am missing something.
