### ISSUE TITLE
Windows gitbutler is changing my file permissions in the git from 644 to 755

### ISSUE THREAD

**Issue by 700software** [gitbutlerapp/gitbutler#3329]
Sorry no repro details right now just wanted to mention. Feel free to close if you are tracking this a different way.

**Comment by krlvi** [comment]
Thank for reporting this! We are gonna investigate whats causing this

**Comment by Qix-** [comment]
We can definitely make a fix for this to work a bit better. For now, try `git config --local core.filemode false` in your project repository. Use `--global` instead of local to make it apply to all of your repositories by default. Hopefully libgit2 picks that up.

This is because Windows doesn't have file permissions bits like *nix does, so it defaults to marking everything you add as "executable" because this most closely mimicks how Windows treats files on the filesystem.

---

@krlvi we could, in theory, first check the config using the "auto" scope to see if `core.filemode` is set to anything other than a false-ey value. If we get what's effectively a `None`, we can default to `false` and then pass that to whatever Git operation is being executed as "one-off" config (so as not to write the config back to the repository).

Doing it that way would default to (what is IMO) a more realistic and interoperable default these days, with the added ability for users to switch it back on later if they want.

Another way of doing it is just creating a UI config option that fetches/sets that value at the project level, assuming libgit2 honors config like that. To be complete we'd probably need a three-state checkbox - true, false, and "unset" (fallback to default).

Let us know if this helps @700software :)

**Comment by othrayte** [comment]
@Qix-, I tried setting core.filemode to false however my files are still getting changed from 100644 to 100755. I wasn't sure whether by "... marking everything you _add_ as ..." you are referring to only new files, but to be clear, at least in my case the issue affects both added and modified files.

This is quite the issue for me otherwise testing out GitButler as I have to manually rewrite every git commit and remove the mode change, which then confuses GitButler because what it thinks the branch should contain and what the normal local branch and remote contain has this mode difference. Hopefully we can find a working workaround.

**Comment by Qix-** [comment]
Yeah we're planning on adding commit support to the `System Executable` auth mechanism that would honor the configs, but it'll be a while before that's out. Sorry you're hitting that :/ I'll see if I can find some time to work in some sort of patch at some point.

**Comment by Byron** [comment]
I looked into this briefly and saw that right now, GitButler is setting the executable bit forcefully on Windows:

https://github.com/gitbutlerapp/gitbutler/blob/f4a8aa5592fb74cc7f75b3a0517201e5c1f61dad/crates/gitbutler-core/src/virtual_branches/virtual.rs#L2131-L2134

In Git, `trust_executable_bit` is `true` if `core.filemode` is true. On Windows, this is `false` by default I presume, which [seems to mean](https://github.com/git/git/blob/00e10ef10e161a913893b8cb33aa080d4ca5baa6/read-cache.c#L206) that Git assumes `644` rather than `755`.

Could a fix mean to prefer mode `644` on Windows rather than `755` until the `core.filemode` handling is figured out? Probably I am missing something though.

**Comment by Qix-** [comment]
Right, forgot I added that when we were in a dash to get windows support up and running. Seems we just need a config check there. :) I was trying to match Git's default functionality which I thought I checked was `true` at first, but maybe I was wrong.

PR welcome, though preferably we do a config check instead of forcing back down to non-executable.

**Comment by Byron** [comment]
I looked into this for a moment and realised that there is no way to 'emulate' an executable bit on Windows, which determines this by file-extension exclusively. Git doesn't seem to care, unless there are patches in "Git for Windows" which I don't have to look at here.

The resources I checked was the `std`-library and `rustix`, which [has some Windows-specific data](https://doc.rust-lang.org/nightly/src/std/os/windows/fs.rs.html#304) but it's nothing related to executable bits.

Hence I think the best intermediate solution is to not enforce the executable bit, even though that might miss executable bits that are actually set. Handling that would be out of scope for this fix for now, but I think it can be tackled by creating a new issue for this right away - it seems to be the smaller of both evils.
