### ISSUE TITLE
Data loss when branch switched outside gitbutler

### ISSUE THREAD

**Issue by bioshazard** [gitbutlerapp/gitbutler#3339]
I started using this today. Was glad to finally separate my uncommitted scratch work away from my active development. I split my uncommitted scratch work to a couple virtual branches. I was a little confused about an aspect of the interface so I switched my branch off the integration branch and lost all my uncommitted virtual branch data. There was a "return to using GitButler" button but it wasn't working. I removed and readded my project.

How do virtual branches work? Is it git stash? Is it in some cache in GitButler? I should be committing stuff that matters but it seems like my data loss even with my many blunders could have been avoided. Thoughts?

**Comment by krlvi** [comment]
Hey! Let me try to help. When you select "return to gitbutler" did you get any error message or toast? The reason why I am asking is that if you switched to another branch with just git, and if you had uncommitted changes, GitButler will insist that you stash or commit that before coming back to GB (in order to protect changes made there).

Regardless of that though, any vbranches that you create are always written out as git trees, and you can find a reference to them in `ls -l .git/refs/gitbutler` in your repo. Because they are namespaced, they will not show up in branch listing, but if you get the reference from the file, you can check it out, or cherry pick from it etc. The commits will be there as well as the uncommitted work will be in the top-most commit. 

Here is a more detailed guide on extracting data from GitButler - https://docs.gitbutler.com/troubleshooting/recovering-stuff
Let me know if this helps

**Comment by bioshazard** [comment]
Appreciate the prompt support here. Will check at with tomorrow and report back!

**Comment by bioshazard** [comment]
@krlvi , ok so I see all my virtual branches from before per the recovering document you linked. I would consider the immediate scope of this issue RESOLVED. However, I am curious: Has your team considered adding functionality in the workspace UX to allow the user to recover these virtual branches? Would be powerful to expose them with a simple "recover" button.

**Comment by bioshazard** [comment]
Gotta say, I have found adoption very confusing when I have existing branches. Going to return to GitButler after I completely clear my workspace.
