### ISSUE TITLE
Make the ephemeral gitbutler/integration commit with the user as committer

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#3342]
The commit is ephemeral, but it would be less surprising this way

**Comment by Caleb-T-Owens** [comment]
I'm not sure this is better. It might even make it more confusing.

If I apply a branch with commits from someone else, they're now going to be shown like they're from me.

If I'm using a tool like GitLens, it does appear like its from "GitButler", but if I hover over the commit, it lets me know what is really going on.
![Screenshot 2024-03-28 at 19 21 20](https://github.com/gitbutlerapp/gitbutler/assets/13354155/c61c56e3-0c0d-48d0-8181-5b2fed7ce81f)

**Comment by Caleb-T-Owens** [comment]
So, from what I can tell, we're merging together all the commits from each of the vbranches in `update_gitbutler_integration`. If we're wanting them not to appear as belonging to gitbutler/integration, it would be better to perform a cherry-pick-like operation on all of the commits to bring them into gitbutler/integration. It would make it a little bit harder to keep track of them all, but would achieve better UX over-all.

<img width="975" alt="Screenshot 2024-03-28 at 19 39 26" src="https://github.com/gitbutlerapp/gitbutler/assets/13354155/e2b5e0e6-9d72-489d-8807-bdfe83e755d6">

**Comment by DiogoM14** [comment]
In my opinion if the make this change, it will be clear that the user is the one making the changes and their email will be associated with the changes. To avoid confusion, I believe that we should display the user's name instead of GitButler's name when registering code changes. This way, it will be clear that the user is the one making the changes and their name will be associated with that.

  The mention of GitButler is unnecessary as the changes will ultimately be registered under the user's email.
