### ISSUE TITLE
Invalid null OID

### ISSUE THREAD

**Issue by schacon** [gitbutlerapp/gitbutler#3542]
I've seen this personally, but also from some users. It looks like some issue adding binary files to the tree.

```
error=failed to handle virtual branch event
 
Caused by:
    0: failed to list virtual branches
    1: failed to write updated tree
    2: failed to insert entry: invalid null OID - image.png; class=Tree (14)
```

This is a tracking issue to gather more data.

**Comment by joshweier** [comment]
This error occurred for me as well.

After not being able to recover from this I manually merged the changes to capture them, then wiped out my GitButler app settings. When I went to re-add the project I had been working on, I got a message telling me that submodules were not supported by GitButler and I'm now unable to use it for the only project I need it for. 

That aside, I'm wondering if the error came about due to having a submodule-using project that entered into the GitButler universe before that restriction was put in place.
