### ISSUE TITLE
Enable GitButler Features Slider by Default

### ISSUE THREAD

**Issue by neerajjain92** [gitbutlerapp/gitbutler#3935]
<img width="595" alt="Screenshot 2024-05-31 at 11 37 32 PM" src="https://github.com/gitbutlerapp/gitbutler/assets/11440750/c9f413d5-a5e9-4d84-9cc4-0d1691e20918">

I would like to request that the GitButler features slider be enabled by default, rather than requiring the user to manually toggle the settings. This would provide a more seamless and user-friendly experience, as the automatic branch creation and pull request generation features are valuable for streamlining the development workflow.

Thank you for your consideration.

**Comment by krlvi** [comment]
Hey thank you for bringing this up! I think there is a small tradeoff here between convenience and being predictable with the defaults. Because this feature requires sending of code snippets to an LLM endpoint (OpenAI or Anthropic), we wouldn't want a developer to accidentally have this enabled by default. For example their customer or employer might have a policy against that.

On that note, since release 0.12.0, the app supports local LLMs via Ollama, but the app can not assume that it has been setup ahead of time. 

I hope you don't mind, I will close this as "not planned" for the time being. Feel free to open other issues with any other things that you come across.
