### ISSUE TITLE
Feature Request: Open in VSCode in a New Window

### ISSUE THREAD

**Issue by l-melon** [gitbutlerapp/gitbutler#4037]
Currently, when clicking "Open in VSCode" in GitButler, it opens the repository in the existing VSCode window. It would be more convenient if this action could open the repository in a new VSCode window instead, allowing users to keep their current work uninterrupted.

**Comment by Byron** [comment]
This seems like a good improvement!

The current behaviour opens the file in the last active VSCode window. This means, if a new Window is created before clicking links in GitButler, the files will be opened in the newly created window, as opposed to the project window one might have had open before.

If vscode links support affecting this behaviour, it would also be important to not open a new window for each file. But maybe that could be something left to the user (i.e. a separate flag/button saying "Open in new window" or equivalent).

**Comment by l-melon** [comment]
When running `code <file path>` in the terminal, VSCode will open the file in the last active window, while `code <folder path>` will trigger the opening of a new window. This behavior remain consistent when using the `Open with Code` optione from the file exploer.
To control whether a new window is opened or not, I think can use the `--new-window` or `--reuse-window` argument.
![image](https://github.com/gitbutlerapp/gitbutler/assets/71011125/3b08544e-b8f2-4d48-8669-d00b3fe4c6be)

[VSCode CLI options](https://code.visualstudio.com/docs/editor/command-line)

**Comment by Byron** [comment]
Thanks for researching this! 

As far as I know, we are using the `vscode:://<filepath>` URL scheme which is then opened using the [`open` crate](https://crates.io/crates/open) *(via tauri)*. There one might also be able to pass parameters, and it [seems like](https://stackoverflow.com/a/72832716/651368) `windows_id=_blank` can be used to open something in a new Window.

CC @krlvi and @PavelLaptev to see if this fits into the UI/UX part of the application so that would be easy to use. Because if it makes sense, it would certainly be easy to implement.

**Comment by Caleb-T-Owens** [comment]
On the flip side, 95% of the time when I'm using gitbutler, I've got the same project open in vscode and gitbutler, and I'll use the "open in vscode" utility to jump to a particular hunk instead of navigating through vscode, and opening in a new window would not be desirable.

If we were to add in this functionality, I would be keen to retain the existing behaviour in a convenient manner.

I wonder if we could do a macOS style "holding shift" functionality which would change the items in the context menu to show a second variant which would be open in new window

**Comment by Byron** [comment]
I love the idea of holding shift, or having some sort of modifier. Middle clicks on links usually open them in a new tab, maybe some sort of (maybe more obvious) modifier can also be used. What if the menu-items change behaviour (and maybe names or icons) if `alt` is pressed on MacOS? 

This is not even a suggestion, just an idea that seemed intuitive in this particular case.

**Comment by PavelLaptev** [comment]
We definitely need to open a project in a new window when using the bar menu.
<img width="229" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/555e786f-521c-4892-ae79-e09e0e672761">

Currently, this menu action opens the project in the last active window, which is not ideal as it overwrites your latest window. When I click on "Open project in VS Code," it implies that the project is not opened yet and should be opened in a new window.

https://github.com/gitbutlerapp/gitbutler/assets/18498712/2f8ee55c-36b7-4a8c-82aa-951f7fbc9510

@Byron will you have time to update this?

**Comment by PavelLaptev** [comment]
I agree with @Caleb-T-Owens. When editing code, most users already have the project open, which uses one workspace per project. Opening a file in a new window or workspace duplicates the project, which is less common than viewing it in the same workspace.

Making files open in the same tab by default would be common for most users. 
Adding a hotkey to switch between opening in a new or same tab is a good idea, but getting more feedback from users could help decide if this feature is really needed now.

Btw, here is an example from macOS:

https://github.com/gitbutlerapp/gitbutler/assets/18498712/2ae61b08-43bf-4827-a9b7-7f462038e01a

**Comment by Byron** [comment]
> Btw, here is an example from macOS:

It's funny that after all these decades on MacOS I wasn't aware this worked there! So useful to be able to force-quit right at the app icon :D.

> @Byron will you have time to update this?

Sure thing, A PR should be up soon (assuming this truly is nothing more than adjusting how a URL is built)!

**Comment by PavelLaptev** [comment]
> Edit: Here is https://github.com/gitbutlerapp/gitbutler/pull/4045

@Byron @Caleb-T-Owens I just checked this PR and found that `?windowId=_blank` works quite well. If the project workspace is not open, it will open it. If the project workspace already exists, VS Code will switch to it.

Given this, I think we could use `?windowId=_blank` in other places as well. Or am I missing something?

Here is an example of how `?windowId=_blank` works with both open and non-existing workspaces.

https://github.com/gitbutlerapp/gitbutler/assets/18498712/366bad02-9446-4bc7-a961-6c6bd8caf61e
