### ISSUE TITLE
[feature request] Manage repositories on remote hosts

### ISSUE THREAD

**Issue by ogvalt** [gitbutlerapp/gitbutler#4081]
Hi there!
Thank you for you great work!

I'm currenty programming from my local machine on remote device (raspberry pi). And I thought that it would be great to be able to use gitbutler on remote device. Like to do everything that is gitbutler is currently doing, but on remote device

**Comment by Byron** [comment]
Thanks so much for sharing!

I have a feeling that it's particularly about being able to use the GitButler UI to control the changes in the working tree, but on the remote device. And if that's true, this issue is very similar to [this one](https://github.com/gitbutlerapp/gitbutler/issues/3795#issuecomment-2167552818).

If you feel that this is the case, please do feel free to close this issue and subscribed to the one I linked. Otherwise, could you specify what the differences are?
Thanks again for your help.

**Comment by ogvalt** [comment]
yes you're correct, but issue that you referred me to is about some auth problem, am I right?

**Comment by Byron** [comment]
Sorry for that, I fixed the link above to [point to the correct issue](https://github.com/gitbutlerapp/gitbutler/issues/4080).

**Comment by ogvalt** [comment]
that guy was first to the party :) 
closing the issue
