### ISSUE TITLE
Branches search bar disappears with scroll

### ISSUE THREAD

**Issue by OJFord** [gitbutlerapp/gitbutler#4123]
### Version

0.12.5

### Operating System

Mac OSX

### Distribution Method

dmg

### Describe the issue

when you scroll through branches scroll bar disappears

### How to reproduce

have more than a full page of branches; scroll

### Expected behavior

sticky search bar

**Comment by Byron** [comment]
I am happy to share something I have recently discovered:

<img width="836" alt="Screenshot 2024-06-19 at 21 44 47" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/55961d9b-11af-42c5-8812-f38d931c46a9">

In the user profile settings, there now is "Always Show Scrollbar", which I think is the same as 'sticky search bar'.
I hope that helps, but otherwise please feel free to reopen in case I am missing something.
