### ISSUE TITLE
Login not working on Linux (AppImage)

### ISSUE THREAD

**Issue by adiletto64** [gitbutlerapp/gitbutler#4149]
### Version

0.12.5

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

![image](https://github.com/gitbutlerapp/gitbutler/assets/72970300/2e568eb5-a20f-48d6-8b77-792eff90da22)

Cannot log in to Github.
I started gitbutler from appimage file. And when trying to log in to Github, it just loads for a second and stops.
And I got this error on dev tools

### How to reproduce

Try to log in to Github using appimage file

### Expected behavior

Should have just login to Github

### Relevant log output

```shell
[Error] Fetch API cannot load https://app.gitbutler.com/api/login/token.json due to access control checks.
[Error] Failed to load resource: Unacceptable TLS certificate (token.json, line 0)
[Error] Unacceptable TLS certificate
```

**Comment by Byron** [comment]
Thanks a lot for reporting!

The app-image has a lot of problems right now as it's more sandboxed than the app would otherwise be, but issue is new to me. What's strange is that the browser-engine refuses to accept the connection, which I thought was outside of the realm of the appimage sandboxing.

Could you provide some details about the GTK version used? The browser-engine definitely affects `tauri`, the framework that is responsible for creating the webviews. [This article](https://www.firezone.dev/blog/using-tauri) has some more details  about it.

**Comment by adiletto64** [comment]
GTK version: 3.24.42

Previous version (0.12.4) installed with flatpak login worked fine (but gitbutler worked slow). So I am waiting the release of 0.12.5 on flathub. Maybe that way it will work

**Comment by mtsgrd** [comment]
It's a bug that this fails silently, but could you confirm that you're talking about GitButler login rather than GitHub login? #4160

**Comment by adiletto64** [comment]
Fixed by installing from flatpak: https://flathub.org/apps/com.gitbutler.gitbutler

**Comment by adiletto64** [comment]
> It's a bug that this fails silently, but could you confirm that you're talking about GitButler login rather than GitHub login? #4160

Ah, yess

**Comment by adiletto64** [comment]
Fixed TLS error with this command on OpenSUSE:
```shell
sudo ln -s /etc/ssl/ca-bundle.pem /etc/ssl/certs/ca-certificates.crt
```
As commented [here](https://github.com/tauri-apps/tauri/issues/4472#issuecomment-1166489867) you should create symbolic link from `/etc/ssl/certs/ca-certificates.crt` to whatever certificate on your distro
