### ISSUE TITLE
Git butler remove all uncommitted changes when setting up project

### ISSUE THREAD

**Issue by vuggy17** [gitbutlerapp/gitbutler#4266]
### Version

0.12.5

### Operating System

Linux

### Distribution Method

deb (Linux)

### Describe the issue

Im new to gitbutler, setting up my first project with my uncomitted changes and everything is gone after it create gitbutler/integration branch

### How to reproduce

I don't want to try it second time :)
but here is my steps: 
install & open .deb package
choose base branch (my case: dev)
lost every uncommitted changes (except unsaved files) in the current branch (foo) 

### Expected behavior

//

### Relevant log output

```shell
//
```

**Comment by Byron** [comment]
I am very sorry to hear that! It might still be possible to [recover the changes](https://docs.gitbutler.com/troubleshooting/recovering-stuff), though.

Just to be sure I tried to reproduce the issue (but used the most recent developer version), but all I could find is that it carried over local modifications and untracked files to the `gitbutler/integration` branch (instead of removing them).

In order to figure out what might have happened there, it would be very useful to get a [peek at the logs](https://docs.gitbutler.com/development/debugging#logs). Maybe they contain errors that give a clue.

Thanks for your help!

**Comment by vuggy17** [comment]
Thank you for replying me,

I just tried again and realized that I might have pressed the delete button while trying to understand what was going on, which caused my changes to be deleted as well (my fault 😐).

I also want to suggest having a modal that warns users about losing uncommitted changes (there is a warning modal when you delete default branch, but not when you unapply it then delete). That would be helpful.

Here is the log in case you still need it: 
[GitButler.log.2024-07-08.txt](https://github.com/user-attachments/files/16140829/GitButler.log.2024-07-08.txt)

**Comment by Byron** [comment]
Thanks for getting to the bottom of this!

It sounds like having a warning prior to deleting an unapplied branch would possibly have prevented this issue!
CC'ing @PavelLaptev for this.
