### ISSUE TITLE
After pushing something goes wrong => Window shows "Something went wrong" text.

### ISSUE THREAD

**Issue by Sagmedjo** [gitbutlerapp/gitbutler#4412]
I do have to restart the client every time I push anything to any branch because after pushing my latest commits, an error message appears saying: "Something went wrong"

**Comment by Byron** [comment]
Thanks for reporting!

May I ask how this issue was created? It somehow bypassed the normal [templates](https://github.com/gitbutlerapp/gitbutler/blob/master/.github/ISSUE_TEMPLATE/1_bug.yml) which would have provided a lot of common (and useful) information from the start.

I think the quickest way to learn more is to [look for errors in the logs](https://docs.gitbutler.com/development/debugging#logs). Typically the UI shows the root of an error, but here it seems to resort to "Something went wrong", which is also unusual to say the least.

**Comment by krlvi** [comment]
I believe that this issue should now be resolved as of the later versions of the app.

Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.
