### ISSUE TITLE
Gitbutler set as author

### ISSUE THREAD

**Issue by einarno** [gitbutlerapp/gitbutler#4677]
### Version

0.12.19

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

As of 12. august all my commits have been assigned to Gitbutler as author. I have not done any changes to my settings apart from upgrading to the latest version. I might have skipped some updates so I'm not sure when this was introduced

### Expected behavior

Use the name and email set in the gitbutler settings

**Comment by Byron** [comment]
Thanks for reporting!

The logic for setting the author name (and the committer) can be found [here](https://github.com/gitbutlerapp/gitbutler/blob/917a46c2ce4e3c10c594ab75e8801f207b82620c/crates/gitbutler-repo/src/repository.rs#L437-L457). It says that if Git does not have the author configured, it falls back to using GitButler as author, instead of failing.

This behaviour might be problematic as GitButler cannot logically be the author.

Using the frontend login information in the backend is something I don't recall was ever available, even though it might be more correct to do that here.

Something I wonder is what happens if you perform a `git commit` on the command-line. Does it find the author information? If it does, can it be that you have configured the author/committer with environment variables?

Thanks for your help in figuring this out.

CC @krlvi, as in any case we probably should rather fail than using GB as author for commits if the commit isn't actually authored by GB (something that right now isn't known here). My fix would be to fail if the author isn't available, even though that would be a problem for all users who have their user configured with environment variables in login shells.

**Comment by einarno** [comment]
Thanks for the swift response, I was missing author name in my git config (only had e-mail), adding it fixed the issue. Don't know why this was changed/removed, but as always the most likely explanation is user error. 

Keep up the good work, I really enjoy using the client both for personal projects and work 😄

**Comment by Byron** [comment]
Thanks for the swift feedback!

I will reopen this issue as I think action will be needed nonetheless - it's better to account for this case instead of putting false authorship into commits which are likely going to be pushed to GitHub.

Previously this may have worked as it might have filled in the email by itself using `gitbutler@gitbutler.com`.

**Comment by Byron** [comment]
For now this is solved by erroring so GitButler won't accidentally pretend to be the author of a commit. In future iterations, it could propose to set the author from the user-interface.
