### ISSUE TITLE
Allow moving any commits from a stack into another lane

### ISSUE THREAD

**Issue by Caleb-T-Owens** [gitbutlerapp/gitbutler#4889]
Currently we only allow moving the top commit of a stack between lanes. This is cumbersome, but done as historically we had no way of resolving the rebase conflicts that might have come out of the operation. Now that we can resolve these conflicts correctly, this is not an issue.

**Comment by Pranav2612000** [comment]
Hey @Caleb-T-Owens ! I'll like to give this issue a try

**Comment by Pranav2612000** [comment]
Hey @Caleb-T-Owens 
I'm trying to understand this issue. Is this ( GIF ) the behaviour we want to improve?

![Kapture 2024-09-24 at 09 12 58](https://github.com/user-attachments/assets/427bf54b-e4c7-4b56-936d-471c13f3d400)

Here, if I move the topmost commit between different lanes, I'm able to do it. But trying to do the same for a non-top commit does not work.
Do we update this behaviour to allow users to move non top commits? What should be the expected behaviour when this happens? Should only the commit being dragged move to a different branch, or all commits from that commit to the top move to the different branch?

**Comment by Caleb-T-Owens** [comment]
> Do we update this behaviour to allow users to move non top commits? What should be the expected behaviour when this happens? Should only the commit being dragged move to a different branch, or all commits from that commit to the top move to the different branch?

The expected behavior would be to have only that 05882e1 commit dragged onto a different lane.

The operation would be to rebase the commits above 05882e1 onto 05882e1's parent, and then rebase 05882e1 on top of the base commit, and then update the heads & trees of the two virtual branches

**Comment by estib-vega** [comment]
Small heads-up. We're about to add some structural changes to this area of the codebase, so I'd wait a bit until those changes make it through.
I'll post an update here once that happens
