### ISSUE TITLE
Need to press "update" twice for merged branches to go away

### ISSUE THREAD

**Issue by ukarlsson** [gitbutlerapp/gitbutler#4905]
Need to press "update" twice for merged branches to go away

This is when my branch is merged upstream.

I would expect that pressing "update" once would remove all merged branches directly.

Many thanks

**Comment by Byron** [comment]
Thanks for reporting!

Assuming you are using the latest version, as of this writing 0.12.25, I tried the following:

* create a commit in a virtual branch
* create a PR using GitButler
* merge the PR in GitHub
* Press the little update button in the PR section of the virtual branch. It then showed the PR as merged.
* Press the little update button next to `Target` so the `Update` button next to `Workspace` appered
* Press the `Update` button and the single merged branch went away immediately.

Can you help me figure out what else is needed to reproduce this issue?

**Comment by ukarlsson** [comment]
Hello!

I think my workflow is

create a commit in a virtual branch
create a PR using GitButler
merge the PR in GitHub
Press the little update button next to Target so the Update button next to Workspace appered
Press the Update button first time and some state seems to be updated in the VB
Press the Update button a second time and the VB goes away

I'll try make a screen recording

**Comment by ukarlsson** [comment]
Yes, version 0.12.25

**Comment by ukarlsson** [comment]
Ok, could not reproduce now

**Comment by mtsgrd** [comment]
To me this sounds like what happens when there are upstream new upstream commits since your last fetch. The first update click will update it the currently fetched upstream commit, but that in turn triggers a fetch revealing further upstream commits.

@PavelLaptev @krlvi do you guys have any thoughts on how we could improve this? I've run into it myself many times.. but I'm unsure if fetching prior to updating is a good idea, it would introduce a weird delay.
