### ISSUE TITLE
LeftHook commit-msg hooks spawn visible shells before executing

### ISSUE THREAD

**Issue by icorbrey** [gitbutlerapp/gitbutler#4982]
### Version

0.12.26

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

I have a Lefthook commit-msg hook that ensures my commit messages are correct semantic commit messages, and it works correctly. However, when run through GitButler it spawns visible shell processes (seemingly while trying to find the system's Lefthook executable since this can be run on many different platforms). This doesn't happen when I commit via the command line or in VSCode.

### How to reproduce

1. Install a commit-msg hook with Lefthook.
2. Make a change to a file.
3. Commit the changes.

### Expected behavior

No extra windows should appear while waiting for the commit-msg hook to finish.

**Comment by Byron** [comment]
Thanks a lot for reporting!

I think the culprit is in the `git2-hooks` crate which runs a bash [like this](https://github.com/extrawurst/gitui/blob/4cb9500cd93bb4d8c4f09083b612b9be105892a2/git2-hooks/src/hookspath.rs#L119-L129). This invocation lacks the usual `NO_WINDOW` flag to suppress the terminal window from showing up:

https://github.com/gitbutlerapp/gitbutler/blob/39099ba41cd128b13642c72994096f44089feec7/crates/gitbutler-git/src/executor/tokio/mod.rs#L73

A patch for this would have to be contributed upstream, and the only reason I didn't do this right away was that validating it would take quite a while for me. However, in theory, adding the above to the command should fix the issue right away.

**Comment by icorbrey** [comment]
No problem! I'll see if I can get a fix in sometime today

**Comment by icorbrey** [comment]
@Byron I've fixed the functionality upstream (see: https://github.com/extrawurst/gitui/pull/2371), hopefully it doesn't take forever for these changes to be merged in and we can see the benefits in the release build!

**Comment by icorbrey** [comment]
Looks like `git2-hooks@0.4.0` has been released. Should I make a PR to bump the version up?
