### ISSUE TITLE
Force push not detected anymore

### ISSUE THREAD

**Issue by ukarlsson** [gitbutlerapp/gitbutler#5227]
### Version

0.13.2

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

The force push option is not available anymore now when I make changes that should be force pushed. It just wants to push and then I get errors

<img width="1421" alt="Screenshot 2024-10-19 at 19 22 36" src="https://github.com/user-attachments/assets/acd7fad8-8278-4168-9dfd-d3000a4401bf">

**Comment by Byron** [comment]
Thanks a lot for reporting!

In the experimental section of the project settings, is `allow force pushing` enabled?
<img width="789" alt="Screenshot 2024-10-20 at 08 17 14" src="https://github.com/user-attachments/assets/0d55458b-0571-4b66-8598-e7e2d1141d46">

My assumption is that this is the case, because even if it wasn't I would expect the `Push` button to not be available in this situation.

For now I flagged it as `UI`-related as I *think* that it does a lot of the ahead/behind logic.

**Comment by estib-vega** [comment]
Hello @ukarlsson 
Thanks again for reporting!

Another person just reported a similar regression: [see Discord message](https://discord.com/channels/1060193121130000425/1073202153163857920/1297871045998411857)

I'm having trouble reproducing this on the same build.
Could you help me figure out exactly what is the state that triggers this?
It seems like an edge-case we're not correctly handling.

By looking at your screenshots, it appears that the one commit has been updated externally (e.g. someone rebased and force-pushed) after you had already checked-out that branch locally.
Is that correct?

If so, are there any other steps to recreate this?

Thanks in advance and apologies for the inconvenience.

**Comment by ukarlsson** [comment]
Hey, I think I updated in GB from master branch. It was not modified externally. It happened many times 2 days ago, but yesterday and today it has been working better. Not sure if it was something temporary.
