### ISSUE TITLE
More steps for creating VB and PR and branch name now gets called "Lane"

### ISSUE THREAD

**Issue by ukarlsson** [gitbutlerapp/gitbutler#5262]
### Version

0.13.4

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Hello team!

I don't understand this change that was made now so that the local branch name is not generated anymore. It seems like remote and local branch names are now different which is really confusing.

For example the local branch name seems to be "Lane" but there is a different remote branch name and they are not synced.

I feel that this is creating a bit of overhead for creating VB since I need to come up with local branch names manually. Before it was super easy and this is like the killer feature of GB

* write some code
* press generate branch name
* press generate commit message
* create PR

Now there seem to be more steps and clicks.

Many thanks

<img width="1091" alt="Screenshot 2024-10-22 at 12 14 50" src="https://github.com/user-attachments/assets/8c7c6fc5-6201-465a-9547-c52a6730bc08">
<img width="1091" alt="Screenshot 2024-10-22 at 12 13 56" src="https://github.com/user-attachments/assets/fef55762-2619-4e15-a18a-665b35acd5d1">

**Comment by Byron** [comment]
Thanks a lot for letting us know, and thanks so much for describing how valuable this particular workflow was for you. And of course, I am sorry that this doesn't seem to work anymore.

Let me reel in @krlvi who probably knows all about this, and I'd hope the workflow can be restored.

**Comment by ukarlsson** [comment]
Thanks!

After using it a bit more, it would be good if there was a way to only set branch name only once. For example if I generate a branch name I want to use it for both my lane and for the remote branch.

Also there is no AI feature for the VB naming, so that becomes a bit tedious now after switching to AI.

Also, it would be nice if I could set the branch name + VB name before committing like before (now it seems like I need to commit before I generate the remote branch name).

**Comment by ipsquiggle** [comment]
I also am confused about the difference between the "lane name" and the "branch name".

I think I understand the changes overall — there's now a clear separation between the "branch" and the "worktree" — but it's not clear what the two different names imply.

**Comment by Byron** [comment]
Thank you for sharing once again! I truly think that @krlvi would have all the answers here, but @PavelLaptev is very likely to know everything about that as well.

**Comment by krlvi** [comment]
Thanks for taking the time to share your experience @ukarlsson. I can clearly see the problem you are describing. 

The reason for making this change is because in a future release we will allow you to split a lane into multiple branches that are dependent on each other. Where previously a lane used to represent a branch, now it represents one or multiple (dependent) branches. 

Why is that useful? You may have noticed that if you make a change that depends on a commit that precedes it, you can't move that change to a new lane, it is "locked". In those cases, it can be useful to express "stacked" or dependent branches, and to accommodate this, we had to modify the UI.

With all of that said, the UI needs to work well in the "single branch in the lane" state - we are thinking about ideas how to make it nice. In addition, we are also working on a larger UI refresh which is more space efficient than lanes. If you have time and if you wish, you can take a look at the Figma files here https://www.figma.com/design/ShIiR6hI5dzH7sT5L03Jg1/Design-3.0?node-id=748-162943&t=IzmrPiqVkRyauNeC-1 and share your thoughts either here or on Discord.

Once again, thanks for taking the time to make these detailed GitHub issues - let's keep this open as we iterate the existing UI to a better state

**Comment by ipsquiggle** [comment]
Interesting. Reading that, I realized that I had an intuition that lanes were already dependent/stacked, right-to-left. I don't know why I thought that, but it does seem like there's already a useful dimension there...

In any case, I love building stacks, so this seems like a good development. :)

Maybe a simple fix is that when a lane/branch have the default name, and there's only one branch, if either name gets edited, automatically update the other one?

**Comment by ukarlsson** [comment]
Yes, exactly, if there is only one stack, would be great to just sync lane name to the AI generated branch name so I don't need to have different names here, and also don't need to type out branch names. My life goal was to never type a branch name again after I started using GB :)

**Comment by PavelLaptev** [comment]
That's done. I believe we addressed the issue. The lane name is no longer present; the header now displays either the lane's branch name or the stack branches.

<img width="759" alt="image" src="https://github.com/user-attachments/assets/087c3b64-1536-4fcd-811c-2687c08daa69" />
