### ISSUE TITLE
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

### ISSUE THREAD

**Issue by esamson** [gitbutlerapp/gitbutler#5282]
### Version

0.13.6

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

Upon launch, I just get an empty window.

I'm using Fedora 40 (KDE Plasma) with Wayland.

### Relevant log output

```shell
** (git-butler:3207): WARNING **: 21:29:40.424: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
2024-10-23T13:29:40.445664Z  INFO crates/gitbutler-tauri/src/main.rs:64: system git executable for fetch/push: "git"
2024-10-23T13:29:40.445781Z  INFO crates/gitbutler-tauri/src/main.rs:101: starting app version=0.13.6 name=GitButler
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

** (git-butler:3207): WARNING **: 21:30:05.447: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by Keloran** [comment]
if you need to download the old one to get your system working again
```
https://releases.gitbutler.com/releases/release/0.13.5-1375/linux/x86_64/git-butler_0.13.5_amd64.AppImage.tar.gz
```

**Comment by Byron** [comment]
Thanks a lot for reporting!

The compatibility story for the Linux distribution, particularly related to AppImage, isn't great, and sometimes there is no good solution, from my experience.

But also, I am fortunately not the right one to talk to about this, but @ndom91 is and knows all about it.

**Comment by ndom91** [comment]
Hey thanks for reporting this. So EGL is referring to OpenGL. I ran into this yesterday as well and spent a bunch of time going back and forth between different opengl / mesa versions trying to pin this down, I'm on NixOS. Downgrading to the version on the `24.04` nixpkgs (`mesa@24.0.7`) allowed me to run these newer releases again.

What I've found so far:

- Nightly `0.5.826` is the last working version for me ([AppImage download](https://releases.gitbutler.com/releases/nightly/0.5.826-1374/linux/x86_64/git-butler-nightly_0.5.826_amd64.AppImage.tar.gz))
- The diff seems to be very small (https://github.com/gitbutlerapp/gitbutler/compare/nightly/0.5.826...nightly/0.5.827) and has nothing to do with any updates to `libwebkit2gtk` or any other rendering related libraries, which is a bit confusing as to why opengl is all of a sudden complaining.
- So first thing I wanted to do was bisect and try building a copy with/without each one of those commits/changes. Maybe having an `.envrc` messes with the GitHub Actions runner

I'll keep this issue updated once I find something :+1:

**Comment by ndom91** [comment]
So I was able to build `master` locally and run the appimage without issue. However, the nightly generated off of [this branch](https://github.com/gitbutlerapp/gitbutler/pull/5292) removing the `.envrc` did not work. It threw the same error about `EGL_BAD_PARAMETER`.

Fortunately this is only a 2-commit bisect haha, I will try a CI build without the other commit next

**Comment by ndom91** [comment]
So it seems that the GHA Ubuntu 22.04 instance started installing `libwebkit2gtk-4.0-dev` version `2.46.1` as of ~2-3 days ago. As opposed to `2.44.1` previously.

First thing I can recommend is try to upgrade `libwebkit2gtk` on your systems and see if that helps :+1:

**Comment by ndom91** [comment]
So I think I figured it out. Can you give the latest nightly a shot? I've pinned the libwebkit2gtk to the previous version.

- AppImage: https://releases.gitbutler.com/releases/nightly/0.5.835-1389/linux/x86_64/git-butler-nightly_0.5.835_amd64.AppImage.tar.gz
- Deb: https://releases.gitbutler.com/releases/nightly/0.5.835-1389/linux/x86_64/git-butler-nightly_0.5.835_amd64.deb
- Rpm: https://releases.gitbutler.com/releases/nightly/0.5.835-1389/linux/x86_64/git-butler-nightly-0.5.835-1.x86_64.rpm


I put up a PR for this: https://github.com/gitbutlerapp/gitbutler/pull/5301

**Comment by itszero** [comment]
Had the same issue on ArchLinux yesterday and the latest nightly does work on my machine!

**Comment by esamson** [comment]
I can confirm that nightly_0.5.835 AppImage works as expected for me. Thanks.

**Comment by ndom91** [comment]
We're in the process of upgrading to Tauri 2, which requires `libwebkit2gtk-4.1` (as opposed to 4.0 for Tauri v1). 

Unfortunately the latest versions of `libwebkit2gtk-4.1` also exhibits the same issue again. I'm testing also pinning it to an older version, the Ubuntu 22.04 repo also have 2.36.1 available for `libwebkit2gtk-4.1`, but that's ~2 years old so I'd love to figure out a better fix for this.

**Comment by ndom91** [comment]
Came across this issue on the webkit bug tracker: https://www2.webkit.org/show_bug.cgi?id=280239

Looks like they acknowledged that something is wrong on their side there, but then there's been no movement since end of Sept :/

**Comment by binarybaron** [comment]
I apologize for bumping this.

We are having the same issues and haven't been able to find a fix yet. We are running Tauri V2.

**Comment by ndom91** [comment]
@binarybaron no problem, basically doing what they did [here](https://github.com/zmkfirmware/zmk-studio/pull/92) at zmkfirmware should do the trick. 

It seems that the latest version of libwebkit2gtk-4.1 in the Ubuntu 22 and 24 repositories doesn't play well with Tauri. 

Be aware though that using the solution we did and zmk seems to have, by bumping to building with Ubuntu 24, will use Ubuntu 24s version of glibc and therefore block folks running earlier versions of Ubuntu from using your app. 

Alternatively, you could build with Ubuntu 22 and use the previously available version of libwebkit2gtk-4.1 in the Ubuntu 22 repos, however that's like ~2.5 years old and lead to a few CSS bugs in GitButler.

**Comment by binarybaron** [comment]
> @binarybaron no problem, basically doing what they did [here](https://github.com/zmkfirmware/zmk-studio/pull/92) at zmkfirmware should do the trick.
> 
> It seems that the latest version of libwebkit2gtk-4.1 in the Ubuntu 22 and 24 repositories doesn't play well with Tauri.
> 
> Be aware though that using the solution we did and zmk seems to have, by bumping to building with Ubuntu 24, will use Ubuntu 24s version of glibc and therefore block folks running earlier versions of Ubuntu from using your app.
> 
> Alternatively, you could build with Ubuntu 22 and use the previously available version of libwebkit2gtk-4.1 in the Ubuntu 22 repos, however that's like ~2.5 years old and lead to a few CSS bugs in GitButler.

Thanks! For us backwards compatability is quite important. Do you know what the most recent working webkit version on ubuntu 22.04 is that works?

**Comment by jokeyrhyme** [comment]
I wonder if maybe the Linux Tauri build ought to statically link/bundle a known-good libwebkit2gtk?

**Comment by ndom91** [comment]
@binarybaron looks like it's 2.36.0. (https://packages.ubuntu.com/jammy/libwebkit2gtk-4.1-0)

**Comment by Samueru-sama** [comment]
We ran into this issue here: https://github.com/VHSgunzo/sharun/issues/2

Any suggestion besides downgrading? Note that the way we build appimages we bundle all the libs with the dynamic linker so to avoid glibc versioning issues.

**Comment by ndom91** [comment]
Looks like Ubuntu released `libwebkit2gtk-4.1=2.46.4` recently. I tried it out (https://github.com/gitbutlerapp/gitbutler/pull/5816), but unfortunately I got the same `EGL_BAD_PARAMETER` issue on my nixos desktop. On my Ubuntu 24.04 VM it seemed to work however. Curious what other peoples experience with `2.46.4` is

**Comment by SpeeQz1** [comment]
I ran in a similar issue when bundling my Tauri 2.0 app on Linux Mint 22 Cinnamon with Nvidia and then trying to test it in a Fedora VM.
`Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...`
It runs normally in a Linux Mint VM strangely.

**Comment by ndom91** [comment]
Hmm odd that it worked for you in a VM as well. EGL is referring to opengl (often provided by the mesa pkg of your distro) afaik, I bet the qemu video adapter driver is just older / better compatible than the amdgpu/i915/xe/nvidia or whatever we're using on our native installations. 

I don't have the time to do a deep dive here, but I'm keeping my eyes on the libwebkit2gtk-4.1 releases hoping they'll work without issue on native installations soon again 🤞

**Comment by SpeeQz1** [comment]
> Hmm odd that it worked for you in a VM as well. EGL is referring to opengl (often provided by the mesa pkg of your distro) afaik, I bet the qemu video adapter driver is just older / better compatible than the amdgpu/i915/xe/nvidia or whatever we're using on our native installations.
> 
> I don't have the time to do a deep dive here, but I'm keeping my eyes on the libwebkit2gtk-4.1 releases hoping they'll work without issue on native installations soon again 🤞

I believe there is some issue when it comes to Fedora as per this issue [here](https://github.com/tauri-apps/tauri/issues/11994)

**Comment by Samueru-sama** [comment]
> @ndom91 I ran in a similar issue when bundling my Tauri 2.0 app as an AppImage on Linux Mint 22 Cinnamon with Nvidia and then trying to test it in a Fedora VM. `Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...` It runs normally in a Linux Mint VM strangely.

Do you have the issue with this AppImage that bundles webkitgtk? 

https://github.com/probonopd/PrusaSlicer/releases/tag/continuous

**Comment by ndom91** [comment]
> Do you have the issue with this AppImage that bundles webkitgtk?
> 
> [probonopd/PrusaSlicer@`continuous` (release)](https://github.com/probonopd/PrusaSlicer/releases/tag/continuous)

No, so for me the latest PrusaSlicer AppImage release (`2.9.0-rc1-x86_64`) seems to run without issue

**Comment by ndom91** [comment]
Hey everyone, so it looks like Ubuntu's released an update to `libwebkit2gtk-4.0` and `..4-1` in their repositories for Jammy (22.04) and Noble (24.04) - `2.46.5`.

I gave it a shot with our application [here](https://github.com/gitbutlerapp/gitbutler/pull/5955) and it seems to have fixed the dreaded "white screen" issue on render. 

With `libwebkit2gtk-4.1@2.46.5` I was able to remove the version pinning back and build on `22.04` - thereby supporting folks using Ubuntu 22.04 as well again :pray: :raised_hands: 

Wondering if anyone else has luck with `2.46.5` too?

**Comment by olekolek1000** [comment]
@ndom91 
I'll just add my two cents. I'm in the middle of creating a GitHub runner for my separate project (VR dashboard app) with the webkit2gtk at `2.46.5`, no luck running on my local machine with Arch Linux (logs after startup):

```
** (WebKitWebProcess:59699): WARNING **: 23:36:12.129: Error loading the injected bundle (././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so): ././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so: cannot open shared object file: No such file or directory
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```

[My workflow file](https://github.com/olekolek1000/wayvr-dashboard/blob/workers/.github/workflows/build.yml)

Maybe I'm doing something different, but overall this workflow should work the same as yours.

**Comment by Samueru-sama** [comment]
@olekolek1000 that error you have is because you are missing `libwebkit2gtkinjectedbundle.so` in the `AppDir/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle`. The entire `injected-bundle` dir is missing as well.

[The only way we managed to get this all to work](https://github.com/VHSgunzo/sharun/issues/2) was to bundle **all** the libs, including the opengl ones, this also means copying `/usr/share/glvnd` to the AppDir and include it in `__EGL_VENDOR_LIBRARY_DIRS`.

**Comment by olekolek1000** [comment]
@Samueru-sama  Thanks for the clarification. I’ve just made a quick-and-dirty way to copy all required libraries directly into tauri.conf.json, without using `ld-preload-open` for now:
```json
"bundle": {
         "linux": {
                 "appimage": {
                         "files": {
                                 "/usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0": "/lib/x86_64-linux-gnu/libGLX_indirect.so.0",
                                 "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0": "/lib/x86_64-linux-gnu/libGLX_mesa.so.0",
                                 (... many other libs ...)
                                 "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so":"/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so",
                                 "/usr/lib/x86_64-linux-gnu/libLLVM-15.so.1":"/lib/x86_64-linux-gnu/libLLVM-15.so.1",
                                 "/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0":"/lib/x86_64-linux-gnu/libEGL_mesa.so.0",
                         }
                 }
         },
         "active": true,
         "targets": ["appimage"],
         "icon": ["icons/icon.png"]
 }
```
That definitely fixed these two errors, but another one is showing up: `libEGL fatal: did not find extension DRI_Mesa version 1`.
As you mentioned, copying /usr/share/glvnd/* would probably solve this issue. However, I’m concerned that Tauri’s AppImage build script doesn’t support creating directories, making it impossible to copy anything to the non-existent /share/ directory in the AppDir, forcing me to create a completely separate builder script just to get this working. I will notify you later about my progress regarding that. This issue is definitely something Tauri should address in the upstream.

**Comment by Samueru-sama** [comment]
> @Samueru-sama Thanks for the clarification. I’ve just made a quick-and-dirty way to copy all required libraries directly into tauri.conf.json, without using `ld-preload-open` for now:
> 
> ```json
> "bundle": {
>          "linux": {
>                  "appimage": {
>                          "files": {
>                                  "/usr/lib/x86_64-linux-gnu/libGLX_indirect.so.0": "/lib/x86_64-linux-gnu/libGLX_indirect.so.0",
>                                  "/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0": "/lib/x86_64-linux-gnu/libGLX_mesa.so.0",
>                                  (... many other libs ...)
>                                  "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so":"/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so",
>                                  "/usr/lib/x86_64-linux-gnu/libLLVM-15.so.1":"/lib/x86_64-linux-gnu/libLLVM-15.so.1",
>                                  "/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0":"/lib/x86_64-linux-gnu/libEGL_mesa.so.0",
>                          }
>                  }
>          },
>          "active": true,
>          "targets": ["appimage"],
>          "icon": ["icons/icon.png"]
>  }
> ```
> 
> That definitely fixed these two errors, but another one is showing up: `libEGL fatal: did not find extension DRI_Mesa version 1`. As you mentioned, copying /usr/share/glvnd/* would probably solve this issue. However, I’m concerned that Tauri’s AppImage build script doesn’t support creating directories, making it impossible to copy anything to the non-existent /share/ directory in the AppDir, forcing me to create a completely separate builder script just to get this working. I will notify you later about my progress regarding that. This issue is definitely something Tauri should address in the upstream.

The DRI error is likely because you also need to bundle the `/usr/lib/dri` dir and set `LIBGL_DRIVERS_PATH` to it. 

Newer mesa does not need that variable to be set anymore, those libs are loaded like any other shared library, however the mesa version that's on ubuntu 24.04 doesn't have that change yet.

If I'm not mistaken tauri will also run linuxdeploy-gtk on the produced AppImage, which just complicates things.

>without using ld-preload-open for now

tauri already does something similar to "fix" that issue by running sed on the libwebkit libs patching `/usr` for `././`, and after changing the current working directory to the AppDir this makes the lib find the binaries. This isn't ideal since it changes the cwd is changed before launching the app.

>forcing me to create a completely separate builder script just to get this working

Oh this is needed 😅 this is why I mentioned that using linuxdeploygtk complicates things.

Ideally the CI has to be configured to build the binaries **without building the appimage** and then a shell script is written to deploy the dependencies, should be about ~60 lines of shell, not much but those are one of the most painful  lines of shell you will see in your life lol.

This weekend I'm going to try help a different tauri project bundle webkitgtk, if everything goes right then it should be much easier for other projects to port the changes.

**Comment by olekolek1000** [comment]
Related Tauri issue:

https://github.com/tauri-apps/tauri/issues/11994

By the way, what's the progress? No pressure, of course. @Samueru-sama

**Comment by Samueru-sama** [comment]
> Related Tauri issue:
> 
> [tauri-apps/tauri#11994](https://github.com/tauri-apps/tauri/issues/11994)
> 
> By the way, what's the progress? No pressure, of course. [@Samueru-sama](https://github.com/Samueru-sama)

https://github.com/Tormak9970/Steam-Art-Manager/pull/240

Got stuck because it also turns out Tauri uses a different method to update appimages outside the official one 😫

In any case the script I wrote is all that should take to fix the issue, it is what we did with Prusaslicer to fix the libwebkitgtk issue as well.

**Comment by olekolek1000** [comment]
I've tried and slightly modified your script in the actions. Application launches successfully, the only thing now is that webkit itself is unable to perform any HTTPS connections. HTTP Tauri plugin fetch() works fine though.

![Image](https://github.com/user-attachments/assets/e6ef95ad-50b1-45bb-b141-69fa883c42c7)

**Comment by Samueru-sama** [comment]
> I've tried and slightly modified your script in the actions. Application launches successfully, the only thing now is that webkit itself is unable to perform any HTTPS connections. HTTP Tauri plugin fetch() works fine though.
> 
> ![Image](https://github.com/user-attachments/assets/e6ef95ad-50b1-45bb-b141-69fa883c42c7)

extract the appimage and run the `AppRun` this way: `strace ./AppRun |& grep -i enoent | grep -i lib`

It likely is missing some ssl libraries or similar.

**Comment by olekolek1000** [comment]
These SSL files were attempted to load (ENOENT):
```
/shared/lib/glibc-hwcaps/x86-64-v3/libssl.so.3
/shared/lib/glibc-hwcaps/x86-64-v2/libssl.so.3
/shared/lib/tls/x86_64/x86_64/libssl.so.3
/shared/lib/tls/x86_64/libssl.so.3
/shared/lib/tls/x86_64/libssl.so.3
/shared/lib/tls/libssl.so.3
/shared/lib/x86_64/x86_64/libssl.so.3
/shared/lib/x86_64/libssl.so.3
/shared/lib/x86_64/libssl.so.3
```

These libs were successfully opened by webkit:
```
/shared/lib/libssl.so.3
/shared/lib/libcrypto.so.3
```

Trying to find more clues, this log is quite large obviously :]

**Comment by Samueru-sama** [comment]
mmm I'm not sure what would be missing, no idea how tauri handles https connections either. 

Before I've had that problem of libssl missing.  I've also have had to add stuff like libnss and pkcs11 to fix other networking issues.

Note that `lib4bin` I often run it with xvfb as  `xvfb-run -a -- ./lib4bin -e ...`, this makes `lib4bin` launch the app for 5 seconds with strace to find all the dlopened libraries. I didn't do it in that the example script I shared because I found out that the app refuses to run as root, which commonly happens when the script gets deployed in the CI.

**Comment by olekolek1000** [comment]
It works! Thanks for the hint!
Webkit needs gio modules. Also I've added libssl and libcrypto by default to the list, just in case.
```
./lib4bin -p -v -r -s -k ./usr/bin/wayvr_dashboard \
        /usr/lib/x86_64-linux-gnu/libGL* \
        /usr/lib/x86_64-linux-gnu/libEGL* \
        /usr/lib/x86_64-linux-gnu/libvulkan* \
        /usr/lib/x86_64-linux-gnu/dri/* \
        /usr/lib/x86_64-linux-gnu/libpulsecommon* \
        /usr/lib/x86_64-linux-gnu/libnss_mdns* \
        /usr/lib/x86_64-linux-gnu/libssl.so.3 \
        /usr/lib/x86_64-linux-gnu/libcrypto.so.3 \
        /usr/lib/x86_64-linux-gnu/gio/modules/* <------ This
```

**Comment by Samueru-sama** [comment]
> It works! Thanks for the hint! Webkit needs gio modules. Also I've added libssl and libcrypto by default to the list, just in case.
> 
> ```
> ./lib4bin -p -v -r -s -k ./usr/bin/wayvr_dashboard \
>         /usr/lib/x86_64-linux-gnu/libGL* \
>         /usr/lib/x86_64-linux-gnu/libEGL* \
>         /usr/lib/x86_64-linux-gnu/libvulkan* \
>         /usr/lib/x86_64-linux-gnu/dri/* \
>         /usr/lib/x86_64-linux-gnu/libpulsecommon* \
>         /usr/lib/x86_64-linux-gnu/libnss_mdns* \
>         /usr/lib/x86_64-linux-gnu/libssl.so.3 \
>         /usr/lib/x86_64-linux-gnu/libcrypto.so.3 \
>         /usr/lib/x86_64-linux-gnu/gio/modules/* <------ This
> ```

Good to know. 

I'm trying to PR a webkitgtk hook to `lib4bin` so that most of this gets done automatically. There is one already for [gio](https://github.com/VHSgunzo/sharun/blob/main/lib4bin#L552-L561)

**Comment by Samueru-sama** [comment]
@olekolek1000 The PR has been merged and now `lib4bin` handles webkit2gtk. 

Use [this](https://github.com/Tormak9970/Steam-Art-Manager/pull/240/commits/f25d8fceb14ee9131daa2f8441390a14207b534c) as reference to know what needs to be removed.

**Comment by olekolek1000** [comment]
@Samueru-sama Works flawlessly 👍

**Comment by slarse** [comment]
Massive necro, but this issue is still frequently referenced by others, and the solution I found does not seem to be documented here.

I basically have the exact problem and (almost same) solution as outlined in this issue: https://github.com/OpenAgentPlatform/Dive/issues/265

The underlying problem here (at least for me) appears to be a linking issue Wayland and mesa. My system's mesa driver does not link correctly against the `libwayland-client.so` lib bundled in the AppImage when building with up-to-date libs on Ubuntu 22.04 and 24.04. For some reason, it works well when _not_ building against up-to-date libs, hence the currently pinned libs in GitButler's CI (see #11412).

I don't encounter this issue when running Wayland with Nvidia's proprietary drivers with otherwise very similar systems the same system setup (Intel x86-64, Arch Linux, Wayland, both systems up-to-date).

Some debug from an AppImage I built myself with the latest WebkitGTK and other packages on Ubuntu 24.04 (again, see #11412):

```bash
$ LD_DEBUG=libs ./GitButler\ Nightly_0.0.0_amd64.AppImage
<snip>
    150540:    /usr/lib/libEGL_mesa.so.0: error: symbol lookup error: undefined symbol: wl_display_create_queue_with_name (fatal)
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```

Preloading my system's `libwayland-client.so` fixes the issue for me.

```bash
LD_PRELOAD=/usr/lib/libwayland-client.so ./GitButler\ Nightly_0.0.0_amd64.AppImage
```

https://github.com/OpenAgentPlatform/Dive/issues/265, further suggests to set `LD_LIBRARY_PATH=/usr/lib`. I haven't found the need to do that, but I will be trying this out more tomorrow. Hopefully I can figure this out well enough that we can get some more up-to-date Ubuntu builds going here.

Side note, I still have a _ton_ of errors related to symbol lookup in the `libnss_*` family of packages, but I have that with every GB AppImage I've tried so it just might be something wrong on my end. Doesn't actually seem to cause any real issues for now, but they may need to be bundled in the AppImage.

## EDIT 2025-12-02
After playing around more with the preload workaround, it _works_ but performance is pretty bad, with the XWayland session's CPU usage increasing by an order of magnitude (~5% -> ~50% single core). I can't really tell if it's a compatibility issue or just a performance regression in the libwayland-client.so lib.

**Comment by Byron** [comment]
Thanks so much for sharing!

I also wonder if we get the idea of an AppImage wrong, and if it could (and should?) ship with *all* shared libraries it was built with? That would certainly increase the binary size, but it's a price worth paying if it then 'just works'.

**Comment by Samueru-sama** [comment]
> I also wonder if we get the idea of an AppImage wrong, and if it could (and should?) ship with _all_ shared libraries it was built with? That would certainly increase the binary size, but it's a price worth paying if it then 'just works'.

https://github.com/pkgforge-dev/Anylinux-AppImages (And when done right they are actually smaller btw)

**Comment by slarse** [comment]
> I also wonder if we get the idea of an AppImage wrong [...]

@Byron IMHO this is more of an upstream Tauri issue then GB doing it wrong per se. Arguably, the only current error on GB's part is to compile on too new a system (Ubuntu 24.04), pinning GLIBC to too new a version.

As noted in #11412, the Tauri team (including @Samueru-sama it seems, it's a small world!) is working on migrating to linuxdeploy -> sharun and squashfs -> dwarfs https://github.com/tauri-apps/tauri/pull/12491. I'm gonna try out that fork and see if those builds are more portable. Will report back after.

> [...] and if it could (and should?) ship with all shared libraries it was built with? That would certainly increase the binary size, but it's a price worth paying if it then 'just works'.

I think @Samueru-sama is referring to using dwarfs instaed, which has better compression than squashfs. So binary size would not necessarily increase.

But I don't think we can bundle _everything_ without shoving GPL software in there, which would be a significant license issue. Or even worse, proprietary Nvidia drivers.

In fact, I think bundling LGPL software into an AppImage without proper attribution and directions for how to get the source code might already be a licensing issue.

**Comment by Samueru-sama** [comment]
> I think [@Samueru-sama](https://github.com/Samueru-sama) is referring to using dwarfs instaed, which has better compression than squashfs. So binary size would not necessarily increase.

[Also this which we use to make our appimages](https://github.com/pkgforge-dev/archlinux-pkgs-debloated)

GTK4 apps usually end up being half their original size with these packages.

> But I don't think we can bundle _everything_ without shoving GPL software in there, which would be a significant license issue. Or even worse, proprietary Nvidia drivers.

nvidia releases its proprietary driver linking to glibc 2.11, which is over 15 years old. 

That means as long as the appimage you packed bundles glibc, it will work with the proprietary nvidia driver of the host without problem, sharun has checks to make sure it gets used without issue as well. [The glibc ver the nvidia driver links to is so old that we need to make sure some ancient libs are present lol
](https://github.com/VHSgunzo/sharun/issues/34)

> In fact, I think bundling LGPL software into an AppImage without proper attribution and directions for how to get the source code might already be a licensing issue.

I don't think so, snap has actually been doing this since forever btw. The steam snap which is shipping proprietary software ships its own glibc as well.

**Comment by slarse** [comment]
> > I think [@Samueru-sama](https://github.com/Samueru-sama) is referring to using dwarfs instaed, which has better compression than squashfs. So binary size would not necessarily increase.
> 
> [Also this which we use to make our appimages](https://github.com/pkgforge-dev/archlinux-pkgs-debloated)
> 
> GTK4 apps usually end up being half their original size with these packages.

That's really cool.

And just for your information, you clearly know _way_ more about this AppImage stuff than I do, so do treat everything I say as coming from someone who's just getting into the game. I very well may be flatout wrong about all kinds of things. More so than I usually am, that is.

> nvidia releases its proprietary driver linking to glibc 2.11, which is over 15 years old.
> 
> That means as long as the appimage you packed bundles glibc, it will work with the proprietary nvidia driver of the host without problem, sharun has checks to make sure it gets used without issue as well. [The glibc ver the nvidia driver links to is so old that we need to make sure some ancient libs are present lol ](https://github.com/VHSgunzo/sharun/issues/34)

That's great. How would you recommend we proceed to start using sharun? Use the WIP branch of Tauri mentioned above?

<details>
<summary>Stuff about licenses that is better discussed in #10623</summary>

> > In fact, I think bundling LGPL software into an AppImage without proper attribution and directions for how to get the source code might already be a licensing issue.
> 
> I don't think so, snap has actually been doing this since forever btw. The steam snap which is shipping proprietary software ships its own glibc as well.

I don't want this thread to derail into a license discussion, but it seems relevant as we're discussing bundling even more libs, so I'll answer as briefly as I can.

I can't really say much about snap as I've no idea about how it works, but steam complies with the licensed software it uses by shipping a file called ThirdPartyLegalNotices.doc (and a bunch of other formats, [I've attached the html version here](https://github.com/user-attachments/files/23889877/ThirdPartyLegalNotices.html)). It's usually in `~/.local/share/Steam/ThirdPartyLegalNotices.doc`. You can find that info under `Help -> Legal Information`. That's the kind of stuff that I believe _any_ software that bundles LGPL (or similarly licensed) software needs.

<details>
<summary>Here's what the Steam's legal notice says</summary>

THIRD PARTY LEGAL NOTICES
Steam and other Valve products distributed via Steam use certain third party materials that require notifications about their license terms. You can find a list of these notifications in the file called ThirdPartyLegalNotices.doc distributed with the Steam client and/or a particular Valve product. Where license terms require Valve to make source code available for redistribution, the code may be found [here](http://developer.valvesoftware.com/wiki/Valve_Open_Source). Some geospatial data on this website is provided by [geonames.org](http://www.geonames.org/)

</details>

It really depends on how you interpret [Section 5 of LGPL 2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html) and whether an AppImage is a "work that uses the library" (license does not apply) or a derivative of the library (license does apply).

> However, linking a "work that uses the Library" with the Library creates an executable that is a derivative of the Library (because it contains portions of the Library), rather than a "work that uses the library". The executable is therefore covered by this License. Section 6 states terms for distribution of such executables.

This is clearly written in an era when static linking was much more common than it is today, so I'm a bit uncertain about how it applies to an AppImage, which _technically_ performs dynamic linking. I guess you _could_ consider an AppImage to just be an archive (you can, as stated above, override the linking behavior after all). But the AppImage is also an executable in its own right, and it contains said libraries. So... I'm uncertain. Regardless, I believe that following the spirit of the license would be to include attribution, like Steam does.

</details>

**EDIT**: Just after posting I found that there is already an issue about licenses over here #10263, so I'll put my entire note about license above in a spoiler tag and let's take any further discussion in #10623.

**Comment by Samueru-sama** [comment]
> That's great. How would you recommend we proceed to start using sharun? Use the WIP branch of Tauri mentioned above?

Will later make some demo using the [template](https://github.com/pkgforge-dev/TEMPLATE-AppImage) we have.

> Stuff about licenses that is better discussed in https://github.com/gitbutlerapp/gitbutler/pull/10623

Note in the case of Steam I mean the snap and not Steam itself. Canonical just ships a build of glibc and a quite and a lot of other libs with the Steam snap, there is only one LICENSE file in the snap and it is the MIT of Steam itself xd. Here is the [link](https://api.snapcraft.io/api/v1/snaps/download/NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx_233.snap) to it if you want to inspect it

And yes static linking helps a ton here, but you have to be careful in that case. 

For example [Eden makes its appimage releases](https://github.com/eden-emulator/Releases/releases) with sharun, tha whole app has Qt6 and mesa bundled, they also link ffmpeg statically to reduce the size down to 60 MiB, otherwise the appimage would be 90 MiB when you bundle ffmpeg libs.

They can link statically because Eden itself is GPL3 anyway.

**Comment by slarse** [comment]
> > That's great. How would you recommend we proceed to start using sharun? Use the WIP branch of Tauri mentioned above?
> 
> Will later make some demo using the [template](https://github.com/pkgforge-dev/TEMPLATE-AppImage) we have.

Cool, looking forward to trying that out. The linuxdeploy-made AppImage just isn't cutting it. I've spent a week trying to make it compatible with... anything but the platform it was compiled on. And it just isn't :)

> > Stuff about licenses that is better discussed in [#10623](https://github.com/gitbutlerapp/gitbutler/pull/10623)
> 
> Note in the case of Steam I mean the snap and not Steam itself. Canonical just ships a build of glibc and a quite and a lot of other libs with the Steam snap, there is only one LICENSE file in the snap and it is the MIT of Steam itself xd. Here is the [link](https://api.snapcraft.io/api/v1/snaps/download/NeoQngJVBf2wKC48bxnF2xqmfEFGdVnx_233.snap) to it if you want to inspect it

You're right, that bundles a _ton_ of things in a very AppImage-like format. I believe you, Canonical wouldn't make such a mistake as to misinterpret the GPLs. So I'll just drop this. I don't fully understand how this is compliant, but someone more informed than I does, and I'll just have to take their word for it.

Not to mention that I'm really tired of reading licenses after doing it for the past two hours 🥲 

> And yes static linking helps a ton here, but you have to be careful in that case.

Oh, I meant that if we were to statically link, it would be a _clear_ license violation :). So let's not do that.

**Comment by Samueru-sama** [comment]
@slarse let me know if this works perfectly: https://github.com/pkgforge-dev/GitButler-AppImage/releases/


<img width="1314" height="863" alt="Image" src="https://github.com/user-attachments/assets/23b7bdb0-ab5e-42dd-ab6b-aeda73d44e18" />

**Comment by slarse** [comment]
> [@slarse](https://github.com/slarse) let me know if this works perfectly: https://github.com/pkgforge-dev/GitButler-AppImage/releases/

@Samueru-sama Fantastic, thank you so much for the effort! I've got my hands full over the next couple of days but I will give this a go on a bunch of different machines and distros as soon as possible.

**Comment by slarse** [comment]
@Samueru-sama So sorry, I completely dropped the ball on this. Too much going on with my day job and personal life, as usual.

The reason I'm taking long isn't that I can't quickly just run an AppImage, but that I'm trying to find some time to do my due diligence here. I don't know the pkgforge project so I don't have an innate sense of trust for images and binaries stemming from it. I need to vet things, and it's proving difficult as these are all very niche things.

**Comment by gauze** [comment]
I had same issue above, used the fix for removing wayland libs and now it loads a black screen and nothing else.

$ ./AppRun
14:13:59 ● logger: Armbian Imager logging initialized
14:13:59 ● logger: Log file: /home/gauze/.cache/armbian-imager/logs/armbian-imager_20260506_141359.log
14:13:59 ● main: === Armbian Imager Starting ===
14:13:59 ● main: Version: 1.3.3
14:13:59 ● main: OS: linux x86_64
14:13:59 ● main: Config URLs:
14:13:59 ● main:   - API Base: https://api.armbian.com/api/v1
14:13:59 ● main:   - Board images: https://api.armbian.com/api/v1/images/boards/
14:13:59 ● main: Updater disabled (not running as AppImage)
14:13:59 ● main: Developer mode disabled, using default log level
14:13:59 ● main: Image cache enabled with 20 GB limit
14:13:59 ● picture_cache: Pre-populating asset cache...
14:14:00 ● frontend::app: Not running on Armbian system
14:14:00 ● picture_cache: Pre-populate complete: 405/405 assets processed



NVIDIA card using nouveau drivers
seeing hundreds of lines of stuff like this:
[  526.892009] nouveau 0000:03:00.0: gr: 00100000 [] ch 10 [005ee80000 WebKitWebProces[11857]] subc 3 class 8397 mthd 0d78 data 00000004
[  526.893596] nouveau 0000:03:00.0: gr: DATA_ERROR 00000012 [RT_LINEAR_WITH_ZETA]
