### ISSUE TITLE
"Branch owner" ignores local git config for name and email

### ISSUE THREAD

**Issue by GordonBeeming** [gitbutlerapp/gitbutler#5359]
### Version

0.13.7 (20241025.081525)

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

I currently have my global git config "x'd out" and then each time I clone a repository I use `git me` or `git ssw` (see my alias's and config at https://github.com/GordonBeeming/dotfiles/blob/main/.gitconfig) and this then updates the name, email and signing key for the local repository.

Currently even after running `git me`  on a repository I still get local changes showing as my x'd out user

![GB-Screenshot 2024-10-30 at 10 03 18](https://github.com/user-attachments/assets/061b7717-2c5c-4f3c-b344-253dea2749aa)

Even after a commit using the proper config, I still see the same

![GB-Screenshot 2024-10-30 at 10 03 56](https://github.com/user-attachments/assets/6527f075-dd8f-47e0-98df-466afaff97b8)

Although the commit is done as the correct user... I just need to try understand why the signing is not working correctly with 1Password (it is on another repo... although giving unverified commits... but that's another issue 😅)

### How to reproduce

Set global git config name and email different to the local repository

### Expected behavior

Should also use local repo config

**Comment by Byron** [comment]
Thanks a lot for reporting!

In my setup, the user name is also coming from a global Git configuration, so attempting a reproduction was straightforward. After altering the repository configuration, the `.git/config` file now contained the following as well:

```gitconfig
[user]
	name = new me
	email = foobar@example.com
```

While the UI was open and after this edit was made, the next commit created would show up with the correct user.

However, on the left side, it would still show the user of the first commit in that virtual branch.

<img width="655" alt="Screenshot 2024-10-30 at 07 30 02" src="https://github.com/user-attachments/assets/8b1bbf30-8548-4c18-8ed3-71b685feb276">

And I think this is the culprit here: **The side bar simply does not update the branch in question after a commit was done**.

For instance, with two authors, one being the global one and the other one being the local one, I had to press `CMD+R` before the side-bar would correctly reflect all the authors in that lane.

<img width="660" alt="Screenshot 2024-10-30 at 07 32 44" src="https://github.com/user-attachments/assets/163defed-0017-4a77-ac43-40051ec2ce6b">

To make this work, after each commit the detailed information of the respective lane would have to be updated in the side-bar.

Let me CC @estib-vega for whom this will be an easy fix I am sure :).

**Comment by estib-vega** [comment]
This should be available after version 0.13.11 of the app :)
