### ISSUE TITLE
Branch list doesn't respect timezone

### ISSUE THREAD

**Issue by stevelw** [gitbutlerapp/gitbutler#5718]
### Version

0.14.1

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

The day headings in the left branches pane seems to ignore timezone. For example, a branch created (in GitHub) 3:45am (GMT) is instantly categorised as 'yesterday'. At the same time, an automatic branch marked as created 20 hours ago (i.e. yesterday) is categorised as 'today' above it.

**Comment by Byron** [comment]
Thanks a lot for reporting!

Here is the portion of code dealing with the major headlines, and indeed it seems to *not* work with calendar dates.

https://github.com/gitbutlerapp/gitbutler/blob/d91a35fc49ea4da15ea498583dc0d643615678f2/apps/desktop/src/lib/branches/branchListing.ts#L265-L298

It's likely that the "<count> <unit> ago" labels do something similar.

I agree that it would be much more intuitive of calendar days would be considered instead of 24h chunks of time.

CC @ndom91, maybe that's easy to solve with the right library.

**Comment by ndom91** [comment]
Thanks for the tag. Indeed this sounds like a frontend mix up - I'll assign myself and take a look when I have a few minutes this week :pray:

**Comment by ndom91** [comment]
Should be fixed in #5784 soon :pray:
