### ISSUE TITLE
Create a pull request flow gets reset if the GitButler refreshes the target in the background

### ISSUE THREAD

**Issue by bjeanes** [gitbutlerapp/gitbutler#5840]
### Version

0.14.4

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

I was drafting a pull request in the pop-up. After a few minutes of composing the description, the entire textarea reset to the default contents (PR template in my case), losing all my work. ⌘Z did not restore the contents.

I noticed that the badge next to `Target` showing the age of the text had been reset to show that it had just updated.

**Comment by Byron** [comment]
Thanks a lot for reporting, and apologies for the hassle :/ . I can feel your pain, having lost many comments while entering them into GitHub comment fields as well.

From the description I think it's clear that the background task the fetches the remote somehow affects the UI so that it resets the PR description.

Maybe @estib-vega could take a look?

**Comment by estib-vega** [comment]
@bjeanes This is an annoying issue, sorry for the inconvenience.
Let me fix that.

Thanks for tagging me @Byron !

**Comment by estib-vega** [comment]
@bjeanes I believe I found the bug an just merged a fix for it.
The next release should have the fix in it.

Apologies for the lost work that this bug caused

**Comment by bjeanes** [comment]
All good! These things happen. Thanks for the quick turnaround :)
